### ISSUE TITLE
Regression in Frontend around FST serialization code for KWasm

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1053]
Pull request: FST serializer: fixes to intermittent, concurrency failures ( #1037 ) causes a regression in the KWasm test-suite, as discovered by this PR: https://github.com/kframework/wasm-semantics/pull/284

Reverting that commit on top of K `master` leads to the tests passing (the commit reverts cleanly).

Reproduction steps:

```
git clone 'https://github.com/kframework/wasm-semantics'
cd wasm-semantics
git checkout _update-deps_deps_k
git submodule update --init --recursive
make deps K_BUILD_TYPE=Release
make build -j8
make tests/wasm-tests/test/core/skip-stack-guard-page.wast.run-term
```

It looks like it runs out of memory with the FST serializer changes, but without those changes finishes without running out of memory. For these tests, we have set `-Xmx8G -Xss500m`.

I'm trying with more memory to see if it solves it, but it seems weird that memory usage would go up so dramatically.

**Comment by ehildenb** [comment]
Increasing to `-Xmx16G` fixes the issue for us, but it seems unreasonable to need that much memory I suppose. Is there a reason it takes more memory with the FST serializer?

**Comment by dwightguth** [comment]
This is probably due to the change in the garbage collection algorithm. if you locally revert the changes to checkJava from that PR, does it work again?

**Comment by denis-bogdanas** [comment]
It could be either the garbage collector implementation or the other change in BinaryLoader. Object `FSTConfiguration` was global before but is thread-local now. I see `make -j` is set to 4 max. Hard to believe, but it is possible that 1 instance of this object fits the memory but not 4 instances. Only if it contains some memory leak.

Considering that we haven't seen an OOMError, there was probably a timeout due to GC thrashing. Increasing heap by a smaller amount should be enough. (10G?)

**Comment by ehildenb** [comment]
The example above only runs a single test, so it's not `make -j4` anywhere. On CI it's `-j4`, but it still fails with a single run.

I'll try with the old garbage collection algorithm (by changing `checkJava`), and report back.

**Comment by ehildenb** [comment]
@radumereuta is this still relevant? If not, let's close.

**Comment by radumereuta** [comment]
We changed the serialization method since then.
So probably no longer relevant.
