### ISSUE TITLE
Very slow parse times for KEVM on the Haskell backend

### ISSUE THREAD

**Issue by gtrepta** [runtimeverification/k#1072]
On the latest master commit of `evm-semantics` (848dca83f3dc15d810dbd9277232ca4b3817703d), the haskell backend is taking a very long time (>12m) to parse one of the specs.

```
make build-haskell

make tests/specs/erc20/ds/transferFrom-failure-1-c-spec.k.prove KPROVE_OPTIONS='--dry-run' TEST_SYMBOLIC_BACKEND='haskell'
```

All of the other specs finish parsing in under 200 seconds. But on the java backend, *all* of the tests parse and prove just fine.

**Comment by dwightguth** [comment]
I am still trying to figure out how to solve this issue in a manner that doesn't make the memory usage of K explode, but for now, you can solve this issue by transforming the side condition of the spec so that each `andBool` clause is wrapped in nested parentheses to avoid the need for parsing an associative list.

**Comment by dwightguth** [comment]
There have been several significant improvements to parsing performance recently. Please reopen if this is still an issue.
