### ISSUE TITLE
llvm fails to duplicate Set inside functions

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1074]
I have this example where I'm trying to duplicate a set of elements inside some function calls. I eliminate the elements from the first set and then the elements from the second set just disappear. 
```
module TEST
  imports SET
  imports MAP

  syntax Map ::= parse(Set) [function]
  rule parse((SetItem(X) => .Set) _:Set)
  rule parse(.Set) => .Map

  syntax KItem ::= disambiguate(Map, Set) [function] // comment THIS function attribute and it works
  syntax KItem ::= init(Set)
  rule init(S) => disambiguate(parse(S), S)
  configuration <k> init(SetItem(1) SetItem(2) SetItem(3)) </k>
endmodule
```
Usage: kompile and krun
Version: 0ef1a6f987c0361e43015d17f8439ebf001f6342

Expected:
```
  disambiguate ( .Map , SetItem ( 1 )  SetItem ( 2 )  SetItem ( 3 ) )
```
Actual:
```
disambiguate ( .Map , .Set )
```

**Comment by dwightguth** [comment]
Several things seem to be happening here. First, `disambiguate` is a function, but you have defined no rules for this function, so the function gets stuck, aborting rewriting. It is supposed to return the stuck function application when this happens, but somehow the stuck function application generated by the backend is missing the elements of the set.

That being said, while you are getting the wrong error message from the backend, this code technically rewrites correctly, insofar as that its correct semantics is that the function evaluation gets stuck and that does indeed happen. Moreover, the problem is not with evaluating the function itself because when I give a semantics to disambiguate, the substitution the function sees is in fact correct. So whatever error you're seeing is specific to the error message that gets reported when function evaluation gets stuck.

I will investigate further and try and come up with a fix, but your definition is also wrong somehow if this is the behavior you are seeing.
