### ISSUE TITLE
[Error] Critical: I/O Error while executing

### ISSUE THREAD

**Issue by gleguern** [runtimeverification/k#1114]
Hi,

I'm having a strange bug. I created the following MWE from my K files [mwe-environment.zip](https://github.com/kframework/k/files/4236494/mwe-environment.zip)

 Compilation goes fine. If I run 8 steps (--depth 8), everything goes fine and I seem to reach a final configuration. But if I run 9 steps or run till completion, I get the error:
> [Error] Critical: I/O Error while executing
> (./.krun-2020-02-21-15-27-53-392-2bf2e463-858f-491a-a33d-f365824a42de/result.kore
> (No such file or directory))

As if the file was deleted before completion.

Any idea what's going on ?

Thanks,

**Comment by dwightguth** [comment]
This error typically happens because the llvm backend crashes while rewriting. It might be a bug, or you might be dividing by zero or something. Newer versions of k make it clearer what happened. If you run the program with --debugger and then type `run` followed by `bt` at the debugger console, what output do you get on the command line?

**Comment by dwightguth** [comment]
You might also consider trying it with the latest version of k to see if this issue has been fixed already; there have been several fixes recently for similar issues.

**Comment by gleguern** [comment]
Hi,
You were right, it was a bug already corrected in the latest version. This MWE works fine with version a7c2937. I have other problems now, but will investigate first.
Thanks
