### ISSUE TITLE
LLVM Backend crashes

### ISSUE THREAD

**Issue by jzw2** [runtimeverification/k#1126]
I'm not sure if this is because I broke my machine or something, but when I try to kompile and krun sum.imp from the k tutorial, I get 

``` [Error] Critical: LLVM Backend crashed during rewriting. ```

I'm running on a mac, I'm not sure what other variables there are that would cause this.

**Comment by dwightguth** [comment]
I'm aware of this issue; it seems to only be affecting macs on recent versions of k. I would suggest installing the latest Homebrew bottle in the meantime.

**Comment by dwightguth** [comment]
Having investigated further, I believe this issue may be fixed with kframework/llvm-backend#303 once the submodule in kframework/k is updated. I'm not 100% sure this is the same issue since I have not independently confirmed it, but it seems to manifest the same way as the bug I discovered, which was a bug caused by the recent release of GMP 6.2, which is also recently released on Mac OS.

As such, if this is the cause of a bug, older versions of K will not fix the problem (unlike my previous suggestion), because it is not so much a regression as a latent bug. You can try to roll back to GMP 6.1.2 and see if that solves it, or you can try building from source and pinning the llvm backend submodule to the branch in the PR I mentioned above, or you can wait and one way or another I will have this fixed soon.

**Comment by dwightguth** [comment]
I believe this should now be fixed. Please let me know if it is still occurring for you.

**Comment by vasil-sd** [comment]
I'm suffering from similar bug, using latest release of K-Tools (v5.0.0-51b354c).

After short investigation, I've found that it crashes on NULL ptr deref in getTagForSymbolName.

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffffd730801 in __GI_abort () at abort.c:79
#2  0x00000000002127a1 in getTagForSymbolName ()
#3  0x000000000021ba72 in allocatePatternAsConfiguration (Pattern=<optimized out>) at /home/jenkins-slave/workspace/k_master/llvm-backend/src/main/native/llvm-backend/runtime/configurationparser/ConfigurationParser.cpp:34

**Comment by dwightguth** [comment]
I need more data about how to reproduce the issue you describe if there's any hope of resolving it. Your stack trace tells me that this definitely isn't the same issue that the original person who created this issue ran into, which is good. It also tells me that it's not an issue on mac OS. But it doesn't tell me anything that would allow me to determine the cause of the error or how to reproduce it, so without that information I can't really take any further action.

**Comment by jzw2** [comment]
Sorry for the late response, but it is now working for me!
