### ISSUE TITLE
Fail to run Makefile in /k/k-distribution/tutorial/

### ISSUE THREAD

**Issue by wenhaosu** [runtimeverification/k#1129]
When I tried to run `make` under almost all folders under `/k-distribution/tutorial/`, I will get the following error message:
`/bin/sh: 1: /mnt/c/Users/suwen/Project_Files/CS422/k/k-distribution/bin/kdep: not found`
`/bin/sh: 1: /mnt/c/Users/suwen/Project_Files/CS422/k/k-distribution/bin/krun: not found`

However, I can manually execute `krun` and other k commands.

The release I've using is the v5.0.0-a7c2937, installed directly in WSL via Ubuntu Bionic (18.04) Package.

![image](https://user-images.githubusercontent.com/19897582/75393715-4b5d8880-58b4-11ea-8ab5-8c25f0267441.png)

**Comment by dwightguth** [comment]
It sounds like you are trying to run the tutorial via a clone of the source code of k, rather than by copying the tutorial out of the /usr/lib/kframework directory into your home directory, as was intended by users of the binary package. Because you are building it from a source directory, the tutorial thinks you have done a source build of k and is trying to use the version that was built, but of course you have not done a source build. It's possible that the build system could be made a little smarter to detect that the version of k it's trying to use is actually a broken symlink, but I think it's probably better if source directories always try to use source builds rather than silently using a version from your path instead if no source build exists. As such you have three options, all of which should work to the best of my knowledge:

1. If you are on a single-user machine, you can just chown /usr/lib/kframework/tutorial into your own user account and then build the tutorial directly from that directory.
2. You can do a source build of k, and then build the tutorial from the source tree. This will take a little longer to build and requires installing some extra dependencies, but it's possible if you want.
3. You can just do something like `cp -R /usr/lib/kframework/tutorial ~` and then build the tutorial from your home directory.

**Comment by wenhaosu** [comment]
Solved by using the third method, thanks!
