### ISSUE TITLE
Support lexical-modes in generated flex scanner

### ISSUE THREAD

**Issue by vasil-sd** [runtimeverification/k#1281]
I've noted that after importing built-in ID module, parser beh. changed, but cannot understand reason.

Without ID, terms like 'a123' are parsed correctly as expected, but after importing ID module, K requires a white-space between 'a' and '123'.

Could someone explain this parser behaviour?

Test case:
```
module A-SYNTAX
  imports INT-SYNTAX
  // imports ID
  /*
  with 'imports ID' K is unable to parse next A terms: 'a123', it demands whitespace between 'a' and '123'
  but without ID terms like 'a123' are parsed w/o whitespaces between them (and it is expected beh.). Why?
  */
  syntax A ::= "a" Int

  syntax Aabs ::= a(Int)
                | abstract(A) [function]
endmodule

module A
  imports A-SYNTAX
  imports INT

  configuration <k> $PGM:Aabs </k>

  rule abstract(a N) => a(N)
endmodule

```

**Comment by ehildenb** [comment]
I'm surprised this ever worked actually. Do you have a version of K where it did work, and can you post it here?

The problem (as I understand it, @dwightguth can confirm) is that you have added the token `a` to your grammar (in two places, once for `syntax A ::= "a" Int` and once for `syntax Aabs ::= a ( Int )`, so the scanner is going to always split the `a` token out as its own token, instead of including it in the identifier that comes after it.

You _may_ be able to fix this by having a separate syntax module where you import `ID`.

```
module A-SYNTAX
  imports INT-SYNTAX
  syntax A ::= "a" Int

  syntax Aabs ::= a(Int)
                | abstract(A) [function]
endmodule

module A
  imports A-SYNTAX
  imports INT

  configuration <k> $PGM:Aabs </k>

  rule abstract(a N) => a(N)
endmodule

module A-PGM-SYNTAX
  imports A
  imports ID
endmodule
```

and using `kompile --main-module A --syntax-module A-PGM-SYNTAX`.

Then you cannot use actual identifiers in your K definition, but you can in your programs.

**Comment by vasil-sd** [comment]
Thanks for reply!

Version of K, I'm currently using, is v5.0.0-3bfd4f8.

reproduction steps:

test.txt
```
abstract(a123)
```

shell commands:
```
> kompile --backend haskell
> krun test.txt
```

output (`imports ID` statement is commented):
```
<k>
  a ( 123 )
</k>
```

But, after uncommenting `imports ID`:

output:
```
[Error] Critical: Parser returned a non-zero exit code: 113
Stdout:

Stderr:
[Error] Inner Parser: Parse error: unexpected token 'a123'.
        Source(/home/vasil/work/panda/isa/semantic/testbed/./t.txt)
        Location(1,10,1,14)
```

Where I can found some details of K parser?
Especially about regexp tokens, their precedence rules, etc.

I've a lot of issues during attempts to implement some parts of concrete domain syntax in K.
So, because of aforementioned issue with `"a" Int`, I've to change to `syntax A ::= r"a[0-9]+"` and strings manipulation in rules.

**Comment by dwightguth** [comment]
I believe this may have worked when k's parser was scannerless, but with the current implementation, there is a lexical ambiguity between `("a" "123"):A` and `"a123":Id`. I would encourage you to think about the design of your language and how to make it less ambiguous.

**Comment by vasil-sd** [comment]
>  with the current implementation, there is a lexical ambiguity between ("a" "123"):A and "a123":Id

But why? I did not use `Id` at all.
configuration was `<k> $PGM:Aabs </k>`, and in syntax of `Aabs` `Id` do not participate.

I cannot understand logic of lexer/parser. Why non-used syntax productions interfere with used ones?

BTW: unfortunately I have to parse already specified language and cannot change its syntax in more K-friendly way :(

**Comment by dwightguth** [comment]
The scanner can't know what nonterminal you are parsing; that is the domain of the parser. You have introduced both `Id` and `"a" Int` to your grammar, thus the scanner contains the terminals from both productions. This means that `a123` is scanned as an Id, even though you have not referenced Id in this particular nonterminal.

You have roughly 3 choices:

1. Use a scannerless external parser to parse your programs. I wouldn't recommend this approach as it's more difficult than the other two, but it's one possibility open to you.

2. Modify the syntax of identifiers in your language to specifically exclude the letter a followed by a sequence of digits. This would mean not using the Id sort, but the Id sort isn't really special; you can easily copy its implementation for your own sort and everything will still work if you do it right. You would then have to subsort A into that sort and write some rules to transform an A back into your identifier sort depending on where it appears, unless your language forbids a123 to be an identifier.

3. Do what you describe and make the syntax of A using a regular expression terminal, then use the `prec` attribute to make the scanner choose your production over an identifier. This has the same problem that `a123` would no longer be a valid Id, if that's something you still want.

One thing we have thought about trying to implement is lexical modes in K. There is no such functionality currently, but if you are unhappy with all three of these solutions, such a solution might solve the problem by making it so that you enter a different lexical mode depending on the terminal prior to the nonterminal A, and then it could choose the correct token because it picks it based on the mode. Depending on your grammar, this may also solve your problem, but it would require a code change. Let me know if this is something you want me to try to look into.

**Comment by vasil-sd** [comment]
Thanks a lot!

Now I begin to understand.

So, scanner works on stream of chars , transforming it to stream of lexems, according to all terminals used in syntax productions (which are visible from syntax module used for parsing) and precedence values.
And if I have two terminals, one of which is prefix of another, from different syntax productions then I've to rule this out by subsorting syntax sorts or/and using rules with string manipulations.

like:
  syntax A ::= Id // here expected Id in form a[0-9+], check it later in rules
  syntax Aabs ::= abs(Int) | abstract(A) [function]

  rule abstract(A) => abs(String2Int(subString....))
         requires allCharsAreNumbers(subString(token2String...)) 
  
  etc..


> One thing we have thought about trying to implement is lexical modes in K. There is no such functionality currently, but if you are unhappy with all three of these solutions, such a solution might solve the problem by making it so that you enter a different lexical mode depending on the terminal prior to the nonterminal A, and then it could choose the correct token because it picks it based on the mode. Depending on your grammar, this may also solve your problem, but it would require a code change. Let me know if this is something you want me to try to look into.

Could you please elaborate more on this?

**Comment by dwightguth** [comment]
Well, scanners like flex typically support what we call modes. Basically, in addition to the regular expressions that match characters, you also have a current "mode", and seeing certain tokens while in certain modes moves you into a different mode according to user-specified transitions. The idea being that different modes can translate the same characters into different lexical tokens. But k, which uses flex for scanning under the hood, doesn't currently have a way to switch modes or to specify that certain terminals should be associated with certain modes, which means that you can't really take advantage of this in K. It's possible, depending on your grammar, that you can disambiguate lexically with such a feature. It's also possible that you can't; without seeing the entire grammar, I can't say. You said your language is based on an existing syntax; are there other parsers for that language already existing out there somewhere? Do they use scanners? And if so, how do they resolve this ambiguity?

**Comment by vasil-sd** [comment]
>  The idea being that different modes can translate the same characters into different lexical tokens.

Ok. I've got it.

>  But k, which uses flex for scanning under the hood, doesn't currently have a way to switch modes or to specify that certain terminals should be associated with certain modes, which means that you can't really take advantage of this in K. It's possible, depending on your grammar, that you can disambiguate lexically with such a feature.

And is there any plans to support modes in K scanner? As far as I understand, modes for tokens may be deduced automatically (semi-automatically), upon information from production terminals. It will be great feature, allowing to parse more languages without using tricks for disambiguation tokens/sorts.

> You said your language is based on an existing syntax; are there other parsers for that language already existing out there somewhere? Do they use scanners? And if so, how do they resolve this ambiguity?

It is in-house low-level language, which is parsed ad-hoc by c++ code, without any formal grammar (don't ask me why, I'm not the author of this code :) ).

Currently I've moved all domain-specific tokens into separate module, which is used only during parsing programs. Then subsorting and some string manipulation is used to translate concrete syntax tree into abstract one, which is suitable for dynamic semantic of the language.

**Comment by radumereuta** [comment]
This is not blocking and the performance of the scanner is questionable after such a change.

**Comment by dwightguth** [comment]
I tried an implementation of lexical modes and the performance was bad enough that it's not really a suitable solution to this particular issue. As Radu says, there are several potential workarounds. If this is still an issue for you, feel free to reopen.
