### ISSUE TITLE
Difference in treating owise rules by llvm and haskell backends

### ISSUE THREAD

**Issue by vasil-sd** [runtimeverification/k#1322]
Here is reproduction (version of K is tag: v5.0.0-3bfd4f8):

```
module A-SYNTAX
  imports INT-SYNTAX
  imports LIST

  syntax D ::= "d0" | "d1" | "d2"

  syntax V ::= value(D)
             | D

  syntax VL ::= List{V,";"}

  syntax A ::= Int
             | lst(VL,D)

  syntax KResult ::= A | V

endmodule

module A
  imports A-SYNTAX
  imports INT

  rule lst(value(Q); Rest, Q) => 5 [structural]
  rule lst(value(_); Rest, _) => 3 [structural, owise]
  rule lst(_, _) => 1 [structural, owise]


  configuration <k> $PGM:A </k>
endmodule
```

and two cases:

```
$ kompile --backend haskell a.k
$ krun p.txt
<k>
  3
</k>
```

and

```
$ kompile --backend llvm a.k
$ krun p.txt
<k>
  1
</k>
```

haskell backend gives all variants with --search-final:

```
$ krun --search-final p.txt
  {
    Result
  #Equals
    <k>
      1
    </k>
  }
#Or
  {
    Result
  #Equals
    <k>
      3
    </k>
  }
```

but in real k-spec (where I've found this issue), I was not be able to run --search-final with haskell backend because of fault during running spec (I suppose that 16G ram was not enough to make state-space search). 

I understand that there is an ambiguity when one owise rule is a subpattern of another, but there should be some warning, for instance. Or (even better) rejecting such K spec as incorrect.

It seems to me that this sort of check between owise rules could be done via pairwise unification of owise rules, and it could help to reject such malformed owise rules (at least some part of them).

If someone point me to source code places where to start digging, it is possible that I can make such checks by myself.

**Comment by dwightguth** [comment]
This is the deliberate behavior of K; rules with the same priority apply nondeterministically. It's not appropriate to create an error in this case because such an error would reject many correct K definitions. Not all programming languages are fully deterministic in how they are defined, which means that it's necessary to allow nondeterminism in the transition system.

That being said, unintentional nondeterminism is something that it's valuable to be able to detect. I believe the simplest solution would be to add a flag to the Haskell backend that warns during execution whenever more than one rule can apply. I am not responsible for haskell backend development; I will talk to the people involved and see what they say.

**Comment by vasil-sd** [comment]
I understand that non-determinism is normal beh. of system, described by K-specification.

My question is about non-determinism among owise rules. In my opinion, the situation like in aforementioned case, where several owise rules are enabled  simultaneously during execution, is highly likely not wanted and not expected by developer.

As I understand, owise pattern is shortcut to something like that: expanded/translated owise_pattern := 
owise_pattern and not (exists P:ALL_OTHER_PATTERNS, such that P).

So, I've expected, that there should be at most one enabled owise pattern in any given state during execution.

Am I wrong in treating owise patterns?

**Comment by dwightguth** [comment]
The owise attribute simply means that the rule has lower priority than all rules that don't have the owise attribute. (It's a bit more complicated than that when you consider the priority attribute, but I'm simplifying)

Thus, if two rules have the owise attribute, it simply means that both rules have priority lower than all the other rules. They still have the same priority with respect to one another.

**Comment by vasil-sd** [comment]
Aha.
As I've understood, if pattern with higher priority was matched then all patterns with lower priority are just skipped.

And if there are several patterns with the same priority, then there is state bifurcation (point of non-deterministic choice between patterns)?

Is it correct?

**Comment by dwightguth** [comment]
In general, yes, although note this is not true of functions. When a production is tagged with the function attribute, it becomes a function, and of course functions can only have one value for any given input. This is not checked by K currently, but if you write such a function, the prover may be able to prove `#False`, ie, your semantics is logically not consistent, which in general means that proof results over such a semantics are essentially meaningless.

Note: this is not the same as saying that it's an error if more than one function rule applies on a given input. For example, this is a valid axiomatization of logical or:

```
rule true orBool B => true
rule B orBool true => true
rule false orBool false => false
```

Here it is not determined which of the first two rules applies to simplify the term `true orBool true`, but since both eventually rewrite to the same value, the definition is confluent, which means that it's not logically inconsistent. This makes the task of determining whether a set of rewrite rules for a function is confluent or not very difficult, and in general it requires more work than simply checking whether their left hand sides unify. Indeed, it can involve arbitrary computation since you will eventually need to check whether the two right hand sides of each critical pair rewrite to the same term. Since the right hand sides can contain arbitrary functions, in its fullest generality this problem is turing complete and thus undecidable. This is another reason we don't try to attempt to warn the user about things like this; it's just not computationally practical.

However, it may be possible for the haskell backend to be modified to check whether a particular input configuration is confluent; it would be extremely slow, but you could simply explore every path and check that they all reach the same output; however, you still have not solved the question of whether it is confluent for every input, and if the transition relation doesn't terminate, neither will k.

**Comment by vasil-sd** [comment]
Thanks for clarification!

Is there some wiki pages/docs, etc where newbies like me can read about priorities in rules, functions and their limitations/nuances and so on?

BTW: I've noted some issues in `requires` conditions in rules:

```
module A-SYNTAX
  imports INT-SYNTAX
  imports BOOL-SYNTAX

  syntax BoolExp ::= Bool
                   | Exp "==" Exp [seqctrict]
                   | a(BoolExp) [strict]


  syntax Exp ::= Int
               | e(Exp) [strict]
               | BoolExp "?" Exp ":" Exp [strict(1)]


  syntax KResult ::= Bool | Int
endmodule

module A
  imports A-SYNTAX
  imports BOOL
  imports INT

  rule a(true) => false [structural]
  rule a(false) => true [structural]

  rule true ? E : _ => E [structural]
  rule false ? _ : E => E [strutural]

  rule L::Int == R::Int => L ==Int R [structural]

  rule e(I::Int) => 0
       requires a(I == 1)
       [structural]

  rule e(_) => 1 [structural, owise]

  configuration <k> $PGM:Exp </k>
endmodule
``` 

program in t.txt: `e(2)`

haskel backend gives next result:
```
$kompile --backend haskell a.k
$krun --search-final t.txt
  {
    Result
  #Equals
    <k>
      0
    </k>
  }
#And
  {
    a ( 2 == 1 )
  #Equals
    true
  }
```

but llvm backend cannot even kompile defintion:
```
$kompile --backend llvm a.k
/usr/bin/opt-8: tmp.KHeISIwsvf:4846:7: error: value doesn't match function result type 'i1'
  ret %block* %13
      ^
[Error] Critical: llvm-kompile returned nonzero exit code: 1
Examine output to see errors.
```

As I see, llvm backend expects only Bool sort in `requires` section of the rule definition.

What is limitations/constraints of `requires` parts in rules?

**Comment by dwightguth** [comment]
You need your term in requires to be sort Bool, yes

**Comment by ehildenb** [comment]
@vasil-sd can you confirm that this issue is resolved? If so, can you close it?

**Comment by vasil-sd** [comment]
@ehildenb , yes, I'll close it.
