### ISSUE TITLE
`checkJava` incompatible with Mac

### ISSUE THREAD

**Issue by daejunpark** [runtimeverification/k#133]
`sort -V` is not available in Mac: https://ss64.com/osx/sort.html

https://github.com/kframework/k/blob/2d04ba7f9713344445237101d1c25bccc5dbc012/k-distribution/src/main/scripts/lib/checkJava#L50

**Comment by dwightguth** [comment]
This is unfortunate because of two reasons: first, because comparing version numbers is needed in order to fix a bug involving Java 10, but also more generally because it demonstrates that we cannot rely on the target system having gnu coreutils installed, which makes bash programming much more difficult and probably means we have a number of other bugs to fix elsewhere in the codebase. I will try to fix this on Monday.
