### ISSUE TITLE
Add `--md-selector` option to `kprove`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1330]
KProve currently calls the kompile pipeline, which can take either markdown or k file sources. So we should also add the `--md-selector` option to `kprove` to make sure that people can use tangling on proofs they want to perform as well.

**Comment by ehildenb** [comment]
From Slack, @radumereuta noticed: @dwightguth I have a small problem with --directory  in kprove . @ehildenb found a bug where it wouldn't accept .md files correctly and now I'm trying to add --md-selector  to kprove also. The problem is that DefinitionLoadingOptions.directory is duplicated by OuterParsingOptions.directory. I guess the easy fix would be to remove DefinitionLoadingOptions, but a better fix would be to add DefinitionSaveOptions and change all other apearances. Thoughts?

**Comment by dwightguth** [comment]
This is fixed now,  right?

**Comment by radumereuta** [comment]
No, I haven't had the time to work on it. I will probably start tomorrow since I'm done with classes.

**Comment by radumereuta** [comment]
I ran into a few issues with the fix for this.
There are quite a few dependencies in the front end regarding options for parsing.
The way it is implemented right now, when you run kompile, you use the `--md-selector` to parse the definition.
When you want to parse the spec file in kprove, we replicate the kompile setup from the previous run and parse everything with that. That means we inherit the markdown selector option.

So questions:
1. do we want in kprove a separate option, different from the one used to run kompile?
2. if yes, (note: the spec file includes the main definition) do we reparse the definition files with the new markdown selector from kprove? What happens if they are different? It gives the user greater flexibility, but I see that more like a source for errors.
@ehildenb

**Comment by dwightguth** [comment]
Let's hold off on this for now as the discussion about changing the architecture of kprove will I believe resolve these questions.

**Comment by ehildenb** [comment]
Wait for #1333 to figure out how relevant this still is.
