### ISSUE TITLE
Bison parser generation error

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/k#1369]
The input file linked below crashes the Bison parser generator.

To see the error, download the file linked below and do:

`kompile --backend llvm --gen-bison-parser bison-error.k`

or:

`kompile --backend llvm --gen-glr-bison-parser bison-error.k`

Test file:

https://gist.githubusercontent.com/sskeirik/dd324e228f69b063ee5e8cf7f7ce857a/raw/b115cb72120708dc42f68e9b8c677252fc7f583f/bison-error.k

**Comment by dwightguth** [comment]
Bug is fixed in master branch of Bison. I still have to get the proper disclaimers to the Bison team so they can use my test case in their code base. I sent mine, waiting on Patrick to sign and send me his so I can send it to them. But I believe it ought to be possible to download bison from source control, build and install it, and the issue will be fixed now. I could be wrong, though, it may not have landed yet.
