### ISSUE TITLE
Kast error

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#1400]
The simple way of reproducing the bug is:

```
kast --directory . --input binary test3
```

[kast-bug.tar.gz](https://github.com/kframework/k/files/4891721/kast-bug.tar.gz)

The complicated way:

1. Compile rv-match
2. Create a file called a.c with the following content:
```c
#include <stdio.h>

typedef int (*const SPFP)( int master) ;
int fun_A(int a)
{
    return a+1;
}
int fun_B(int a)
{
    return a-1;
}
#define MY_FUNC \
{\
    { &fun_A, &fun_B },\
    { &fun_B  }\
}
int main(void){


    SPFP my_fun[2] = MY_FUNC ;
    printf("%d\n",my_fun[0](1));
    printf("%d\n",my_fun[1](1));
    return 0;
}
```
3. Attempt to compile a.c with kcc:
```
kcc -fno-native-compilation -Wlint -c -d Test/main.c -o Test/main.o -ftranslation-depth=78245
```
4. Identify the last `k-bin-to-text` command in the output generated by the command above, and run kast on its input file.

**Comment by dwightguth** [comment]
The fix for this issue is proving to be very gnarly. Given that the "appetite" for this task is quite small, I'm going to move it back to the backlog. Basically, at fault is the fact that we are representing binary data as a string, but the encoding we use is not necessarily guaranteed to be able to decode the bytes we receive into valid characters, so we end up with mojibake.

I suggest we just tell the very few people who are likely to run into this problem (basically just people using the old C semantics) to use k-bin-to-text instead.
