### ISSUE TITLE
CircularityException Error after kompile command

### ISSUE THREAD

**Issue by Qais87** [runtimeverification/k#152]
Hello everyone,

I want to extend the IMP language by adding repeat-until-loop into its syntax defintion:

![imp](https://user-images.githubusercontent.com/43268150/45826938-b71de800-bcf5-11e8-9d40-5b1a939f5e30.PNG)

But compiling it with "kompile imp.k" fails. It says:

![error](https://user-images.githubusercontent.com/43268150/45827023-e7fe1d00-bcf5-11e8-8caf-81dbbfba674d.PNG)

K parser seems to have problem with the "> Stmt Stmt" line. What does the ">" mean in this context?

Thanks!

**Comment by dwightguth** [comment]
You have declared that the production `syntax Stmt ::= Stmt Stmt` has a priority strictly less than itself, which is an error. There should probably be a better error message, but that's what's going on. You should delete the duplicate production (probably the first one since I doubt you want repeat to be unable to be a child of a while or if.

**Comment by Qais87** [comment]
Thanks for your help. It helped me.
