### ISSUE TITLE
[KIP] - Provide a semantic-only module-level attribute that causes frontend to emit warning when transitively imported into syntax module 

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/k#1570]
Motivation
----------

Situation: In K, there is no boundary between syntax and semantics. 

Problem 1: This conflicts with library development --- since many libraries are designed to be "semantic-only" --- and not part of the parsed language.

Examples: Modules in `domains.md`, e.g. `INT`, `BOOL`, etc., the blockchain plugin, future third-party libraries.

Problem 2: Faster and simpler auto-generated parsers require more restricted grammars. Typically, semantic-only libraries (especially first-party libraries) use specialized syntactic features that more restrictive parser generators do not support, leading to (a) unexpected crashes (b) slowdowns or (c) unnecessarily complex parser generation process.

Examples: the bison parser

Example K Code
--------------

See one example below --- but this annotation should be applied to any other modules that represent semantic libraries and not syntax.

```
module INT [semantic-only]
  imports ...
  ...
endmodule
```

Documentation
-------------

Suppose the user writes a syntax module:

```
module MYLANG-SYNTAX
  imports INT
  ...
endmodule
```

And does `kompile mylang.k`

Then they will receive a warning (before parser generation begins):

`[Warning] Syntax module MYLANG-SYNTAX recursively imported the library module(s) INT, which may cause the generated parser to accept more input than expected. For more information on this warning, see <url-here>.`

Potential Alternatives/Work-arounds
-----------------------------------

Other approaches:

1. When modules are transitively imported into the syntax module, by default, do _not_ import any functions which are declared in `[semantic-only]` modules. When `- w all` is enabled and this occurs, issue a warning that function symbols have been ignored.

   NOTE: There are potential issues with consistency here --- what does it mean for a function to be part of a semantic-only module that is also exposed through a non-semantic-only module? That case should probably become an error --- but it will rarely happen since this feature is for library builders only.

2. Instead of the attribute being module-level, make it a declaration level attribute, so that there is more control over which symbols are not exported to the parser.

Other notes: These two alternatives have lots of overlap with the exports feature that was discussed earlier as part of a future K grant. In a sense, module exports can be sub-divided into two dimensions:

  - symbols that are exported for the parser
  - symbols that are exported for the semantics

So, if we decide these alternatives are better, we should probably wait to implement this all at once.

Testing Approach
----------------

Depending on the approach used, we would need a way to detect when warnings are generated (or) which symbols were exported to the parser module.

**Comment by ehildenb** [comment]
@dwightguth suggestion: Label modules which are not LR-1 as such so that the bison-generated parser knows to treat them differently.

@radumereuta: we had this problem before. One proposed solution was to add annotations to productions themselves to restrict where those productions can be used (people did not like it). Another solution was to have people specifically say which modules should be used for the parser (eg. `ID-SORT` - declares token sort `Id`, `ID-SYNTAX` - adds productions for `Id`, and `ID-SEMANTICS` - adds rules/operations over sort `Id`), which was more easily used by people (but we aren't enforcing this, it's just a design pattern).

Two things we can take away from this: Probably do want parser generated for a module to be generated from that module signature (including everything it imports, and eventually what is imported only via the module signatures). Second thing is that it's reasonable to warn the user about importing suspicious modules into language parser (eg. importing `ID-SEMANTICS` or `INT` directly into language parser, or importing a module which is overly expressive for the parser tech being used - LR-1 for bison).

Probably should not position ourselves such that we're enforcing things like "this is an appropriate use of the parser", but warning people about problems with their grammar seems reasonable.

Fastest path forward is annotation saying that something will not work well with the Bison parser.

Should be allowed:

```
//module

module MYMODULE
    imports INT
    rule <k> X => X +Int 1 ... </k>
endmodule
```

Should not be allowed:

```
//program

int x, y, z;
x = y +Int z;
```

**Comment by nishantjr** [comment]
I was actually thinking about a alternate mechanism to help with the issue of accidentally importing non-program syntax declaration into syntax modules. The idea is to mark program syntax declarations via a namespace like attribute, and allow only importing those into the syntax module. 

This also allows us to mix program grammar with program semantics, something I know both @ehildenb  and I like.

# Example K Code

```
module FOO-INT-EXPRESSIONS
  syntax Exp ::= Exp "+" Exp [namespace(program-syntax)]
  (... other declaration, including semantic rules and non-program syntax...)
endmodule

module FOO-STATEMENTS
  imports FOO-INT-EXPRESSIONS
  syntax Stmt ::= Id ":=" Exp [namespace(program-syntax)]
  ...
endmodule

module FOO-SYNTAX
  imports namespace(program-syntax) FOO-STATEMENTS
  ...
endmodule
```

# Documentation

K allows `syntax` declarations to be marked with a `namespace(...)` attribute.
Import statements may allow importing only certain syntax namespaces.
Import statements with a namespace specified *do not* import semantic rules.

**Comment by ehildenb** [comment]
We're closing thish because you can use the attribute `not-lr1` on a module to indicate that it should not be imported into the bison parser.
