### ISSUE TITLE
ocaml-less packages

### ISSUE THREAD

**Issue by h0nzZik** [runtimeverification/k#1600]
Could we have an ocaml-free K package (maybe called kframework-lite_5.0.0_amd64_focal.deb ), so that users who do not need the ocaml backend do not have to wait for ocaml build?

**Comment by dwightguth** [comment]
The solution here would be to split k into three packages, one that just contains the postinstall script that installs opam, one that contains just the base k without opam, and then a composite package that depends on both. The downside is we may have to set up a ppa, otherwise we would force users to install all three individually if they want ocaml. I'm not sure how worth it all this extra effort is when we intend to deprecate the ocaml backend.

Another, simpler possibility would just be to remove the ocaml code entirely now, and tell people who are still using the ocaml backend to install ocaml manually. Since internally, that is basically just the old c semantics, it sounds doable. What do you guys think?

**Comment by ehildenb** [comment]
I'm fine with just telling people the steps they need for ocaml dependencies separately in the README if they need it specifically, with a warning that it's being deprecating (also in the README). Then don't include them by default in K install.
