### ISSUE TITLE
Compiling and krun Parser running slowly

### ISSUE THREAD

**Issue by Qais87** [runtimeverification/k#163]
Hello,

I have installed K on my Windows 10 Notebook.
The newest versionof Java is installed and Path variables have been set.

The problem is that both kompile takes ca 20 seconds to be finished and krun 33 seconds!
It runs very slowlyand I don't think that my Notebook is that old. What could be the reason?

I just downloaded the k-master archive and unzipped it. Now I just go into the directory, let's say, \k-master\k-distribution\tutorial\1_k\2_imp\lesson_5> and open terminal here. Commands work flawlessly like "kompile..." and "krun..." but they need in total nearly 1 minute to finish executing which is unacceptable. I also used Windows-Subsystem for Linux => same result. 

What should I do? Please help me.

Thanks

**Comment by dwightguth** [comment]
Can I see the exact arguments you invoked kompile and krun with? I need to understand better the exact behavior you're invoking to get a better idea of the performance involved.

**Comment by Qais87** [comment]
kompile imp.k and krun sum.k

I used these both commands and the parser was working slowly, very slowly.

Am Fr., 5. Okt. 2018 um 19:09 Uhr schrieb dwightguth <
notifications@github.com>:

**Comment by dwightguth** [comment]
There are a couple things you can do to improve performance:

* Pass the --interpret flag to krun. This is not the default for legacy reasons but it should save you from the time needed to link the ocaml binary.

* Start the command `kserver` in the background. This will tell K to aggressively cache as much information as possible, which significantly decreases the time spent booting krun, at the expense that you may experience subtle bugs if you don't restart the server before running kompile again. This has not been made the default either, primarily because it was never written in a manner intended to be robust during iterated invocations of kompile.

* Don't delete the imp-kompiled directory before invoking kompile again. This will make kompile cache the parse of all rules which do not change, which is significant because K's parser is fairly slow.

* Write an external parser: as noted before, K's parser is quite generic at the expense of being fairly slow. If you handwrite a parser and pass it to krun via the `--parser` flag, it will probably be faster than the default parser that krun uses.

* Get a cpu with more cores. This is obviously the solution of last resort, but `kompile` has a massively parallel performance structure, so if kompile is taking 20 seconds this could help a lot. Note that it won't have an impact on the performance of executing a single program with krun, but if you have a number of tests in your test suite, you can run them in parallel, which will also drastically improve the overall throughput.

If you do some combination of these steps, especially the first three which should be possible without any major work, I expect you will see substantial improvement. A lot of effort has gone into optimizing k for industrial use, but it's still quite slow if you don't take advantage of any of its tricks.

**Comment by dwightguth** [comment]
Another thing you could try is to run it on a non windows machine. windows subsystem for linux still doesn't have the best performance in some cases and this could be having an impact of some kind.

**Comment by Qais87** [comment]
Thank you for help. Can you tell me what you mean by "Pass the --interpret
flag to krun."
How should be the command? I tried "krun --interpret flag sum.k" but it
shows an error.

Am Fr., 5. Okt. 2018 um 22:46 Uhr schrieb dwightguth <
notifications@github.com>:

**Comment by dwightguth** [comment]
Er `krun --interpret sum.imp`.

**Comment by Qais87** [comment]
That doesn't work. It says: [Error] Critical: Unknown option: --interpret

Am Sa., 6. Okt. 2018 um 22:31 Uhr schrieb dwightguth <
notifications@github.com>:

> Er `krun --interpret sum.imp`.
>

**Comment by Qais87** [comment]
The first tip helped me. Starting kserver solved my issue. The parser works more faster now.

Thanks!
