### ISSUE TITLE
[KIP] - kx improvements

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1711]
Right now kx is just a bash script with limited functionality compared to the java implementation of krun.
Here are some improvement proposals:
- [ ] cmd line arguments should be parsed by a library (help is manually formatted in a string right now)
- [ ] more modularity. The script is already over 500 loc and growing and it's hard to keep track of things.
- [ ] more error messages and warnings

We had a short discussion about implementing kx in something else
- bash
  - is easy to write
  - fast
  -  doesn't introduce another language in the K repository
- python
  - requires a rewrite of the current script
  - should be fast enough
  - python is already a requirement when installing K but not sure where it's being used
- C/C++
  - hard to write something like krun (lots of calls to external executables and working with files)
  - access to the llvm data structures in case we need some information from the definition

**Comment by dwightguth** [comment]
I tend to disagree with most of these suggestions. First of all, it's not uncommon for tools to have manually written help texts; take a look at GNU Coreutils for example.

As far as "more modularity", it was deliberately written the way it was, as a flatter sequence of logic than krun, which had such a degree of encapsulation that it actually became problematic. We can break the logic into some bash functions if you want so it's more organized, but the flow of the code should still be roughly what it is now, rather than trying to organize the control flow into any kind of hierarchy of abstraction.

As far as error messages are concerned, you really need to be more specific. "More error messages" sounds great, but it's meaningless if you can't tell me specific examples of error messages you think should exist but don't. In the absence of that information, the action item is completely meaningless and might as well not exist.

Finally, I don't think it's productive to rewrite the script in another language; it would just make the script more complex for very little gain. Bear in mind also that the goal is <100ms overhead, which probably actually does preclude python, which takes 30ms just to boot up. C++ is technically an option, but given that c++ has no portable file system library and no high level process invocation library, it's not really a very good one.

**Comment by radumereuta** [comment]
You can only print one error message right now and exit. This might be more relevant to `kompile` though.
For more error messages I will look into the current krun code and see what else is missing and add them to the list.

**Comment by ehildenb** [comment]
Closing this as it's been a long time since we migrated `kx` to the new `krun` script, which is fast (and indeed is intended to be fast, with direct execution paths rather than proper parsing libraries and such).
