### ISSUE TITLE
[Bug] regression tests not parallel are slow

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1748]
Recently have been added a new set of tests which have the option:
```
# There are too many memory-intensive tests to run in parallel.
.NOTPARALLEL:
```
https://github.com/kframework/k/blob/master/k-distribution/tests/regression-new/map-symbolic-tests-haskell/Makefile#L2

I run the integration tests a lot and this makes it really slow for my workflow.

Is there an option to disable parallelization only on jenkins?
@ttuegel said there are some problems with some of the machines.

I can comment that line out, but doing so each time I switch to a new branch is just going to be frustrating and error-prone.

**Comment by ttuegel** [comment]
We are always going to have intermittent failures on Jenkins because the load is going to be unpredictable; it's only a question of how often. One solution would be to run fewer tests in parallel on Jenkins. This would probably make the fastest runs slower, but it's unlikely to affect the longest runs (which are probably over-saturated anyway).

**Comment by ehildenb** [comment]
Post jenkins logs of any failures you notice on this test-suite, so we can try to identify common themes.

We'll also make a PR which removes the .NOTPARALLEL and run it a bunch of times, and post the jenkins logs here as well.
