### ISSUE TITLE
[Bug] kompile --version does not show git commit ID when kompile was installed via brew

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#1785]
This is an issue that was reported to us via the Algorand folks. Apparently when you do `brew install kframework/k/kframework` followed by `kompile --version`, it doesn't know what the branch and commit hash are that it should show. This makes it difficult for K developers to determine what version of K our customers have installed, so it should be viewed as an urgent issue. I have not reproduced locally yet; it's possible that this may affect only certain versions of Mac OS.

**Comment by dwightguth** [comment]
I can confirm this is affecting all users who install via our Mac OS homebrew bottle. What happens is, we build the source tarball on Jenkins, then configure brew to build the bottle by pointing it at that source tarball. Because that source tarball doesn't have a .git directory, when Maven tries to use the build-number plugin to get the git revision and branch name, it can't. As a result, those values don't get baked into the Jar, which means that they are populated with default, bogus values when the user asks for the version of K. We need to either find some way of encoding the version number into the jar that doesn't depend on Maven asking for the information from source control, or else we need to change the way we build the homebrew bottle so that the Maven build there has access to source control information.

**Comment by ehildenb** [comment]
This is somewhat related to https://github.com/kframework/k/issues/1824 where we are brainstorming ways to make use of the K PATCH version number. Recall that the version numbers are called MAJOR.MINOR.PATCH.

The reason I say so is because two proposed solution there (to making it so that we bump the PATCH version number every commit to `master`), exist.

One is:

-  Only ever use automerger to merge K prs.
-  Automerger adds a commit at the end of the PR right before merging it (so tests have passed, it's up to date, and has been approved), and that commit goes through and adjust the PATCH version numbers throughout the repo.

Downside is that the PR is merged without testing the version which has all the PATCH versions bumped.

Another approach:

-   Version numbers throughout the repo are templated (so replaced with something like `%%%VERSION%%%`).
-   Have a file `version` which specifies the MAJOR and MINOR version numbers (as `MAJOR.MINOR`).
-   Have a `release` branch which tracks the `master` branch.
    -   Merges to `master` do not trigger full CI runs, rather it triggers an update to the `release` branch, which also changes the `version` file to say `MAJOR.MINOR.PATCH`.
    -   All the templated `%%%VERSION%%%` throughout the repo are replaced with the contents of the `version` file.
-   Updates to the `release` branch triggers the deployment process (which currently runs against `master`).

I'm leaning towards the second approach, for not having to rely on the automerger to merge all PRs (because sometimes we want to get some things in faster).

This is something I've been wanting to setup for quite some time, that way it's easier to tell users things like "you need at least version 5.1.NNN".

It would also solve the mac problem, because the `release` branch would explicitly contain the `version` file, which would be included in the source tarball which is fed to brew-build-package.

**Comment by dwightguth** [comment]
So your proposed solution is to remove commit hashes from the version message entirely in favor of an incremented build number?

**Comment by ehildenb** [comment]
I'm happy to keep commit hashes in the version message, but it does not seem necessary.

The solution, though, is to store a `version` file directly, whatever that version file contains (commit hash or incremented version number). The difficulty is making sure that the version file is updated correctly on every commit to `master`, which the above description provides a solution for.

**Comment by dwightguth** [comment]
I mean, if we pursue this route in order to solve the problem, we should remove the commit hash, because it won't actually address the lack of commit hash on Mac OS.

**Comment by ehildenb** [comment]
I'll take on implementing this.

**Comment by ehildenb** [comment]
Potential issues:

-   Calling `kompile` in a local source build may crash? Will it know to use the version file (or generate it).
-   What do submodules based dependents peg to? master or release?
