### ISSUE TITLE
MacOS packaging failing with stack stuff

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1802]
From @sskeirik

I'm not sure if we have time to address this now, but I wanted to share some observations about the K deploys.Lately, I have seen one of three behaviors:

    the "Build Homebrew Bottle" phase errors out with the error below;
    the "Build Homebrew Bottle" phase does not error out and instead times out; or
    the "Test Homebrew Bottle" phase times out --- which indicates that error (1) is flaky

Does anyone have any thoughts on this?

```
     [exec] Downloaded ghc-8.10.1.
     [exec] Unpacking GHC into /private/tmp/kframework-20210208-4706-onihpd/kframework-5.0.0/.brew_home/.stack/programs/x86_64-osx/ghc-8.10.1.temp/ ...
     [exec] Configuring GHC ...
     [exec] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
     [exec] ld: unknown option: --version
     [exec] Installing GHC ...
     [exec] install: mkdir /private/tmp/kframework-20210208-4706-onihpd/kframework-5.0.0/.brew_home/.stack/programs/x86_64-osx/ghc-8.10.1: File exists
     [exec] make[1]: *** [install_utils/hp2ps_dist-install_wrapper] Error 71
     [exec] make[1]: *** Waiting for unfinished jobs....
     [exec] make: *** [install] Error 2
     [exec] Received ExitFailure 2 when running
     [exec] Raw command: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/gmake install
     [exec] Run from: /private/tmp/kframework-20210208-4706-onihpd/kframework-5.0.0/.brew_home/.stack/programs/x86_64-osx/ghc-8.10.1.temp/ghc-8.10.1/
     [exec] 
     [exec] 
     [exec] Error: Error encountered while installing GHC with
     [exec]          gmake install
     [exec]          run in /private/tmp/kframework-20210208-4706-onihpd/kframework-5.0.0/.brew_home/.stack/programs/x86_64-osx/ghc-8.10.1.temp/ghc-8.10.1/
     [exec]        
     [exec]        The following directories may now contain files, but won't be used by stack:
     [exec]          - /private/tmp/kframework-20210208-4706-onihpd/kframework-5.0.0/.brew_home/.stack/programs/x86_64-osx/ghc-8.10.1.temp/
     [exec]          - /private/tmp/kframework-20210208-4706-onihpd/kframework-5.0.0/.brew_home/.stack/programs/x86_64-osx/ghc-8.10.1/
     [exec]        
     [exec]        For more information consider rerunning with --verbose flag
```

**Comment by ehildenb** [comment]
From @dwightguth 

this is the line in the above output that triggers the error: `install: mkdir /private/tmp/kframework-20210208-4706-onihpd/kframework-5.0.0/.brew_home/.stack/programs/x86_64-osx/ghc-8.10.1: File exists`

really what we want to do is use /Users/jenkins-slave/.stack instead of having it create a .brew_home/.stack

that would also conveniently solve the caching issue that makes us rebuild stack dependencies every single time

**Comment by ehildenb** [comment]
It really does not matter that it's in the particular same spot @dwightguth mentioned, as long as the Jenkins job which runs every week on the weekend (and populates the Anka caches, with all dependencies installed and the `.stack` directory is also created) and the Jenkins job for K master use the same spot, so that we get maximal caching.

Currently, we are _not_ re-using the Anka-cache created directory, because of various sandboxing efforts by Jenkins. So somehow that created directory needs to be made available to the Jenkins K master job (maybe mounted as a volume or something, who knows?)

**Comment by ehildenb** [comment]
Looks like there is a problem with the PR: https://github.com/kframework/k/pull/1813#issuecomment-779926245

**Comment by ttuegel** [comment]
#1813 fails because Stack lacks the permissions required to create a global cache directory. In #1856, I am trying to use a local cache that will be shared between jobs. I am still having problems with permissions. It seems like Homebrew works hard to lock down permissions within the builder. According to the little documentation I can find, Homebrew intends that formulas with foreign dependencies (e.g. Haskell or Rust) would re-build those dependencies every time the bottle is built. To conform with this expectation, I can disable the Anka Stack cache. It is possible that this interferes with the build, but I'm not sure how. In any case, it's not helping anything.

**Comment by ttuegel** [comment]
Actually, according to [this comment](https://github.com/brewsci/homebrew-science/blob/bb52ecc66b6f9fad4d281342139189ae81d7c410/Formula/tamarin-prover.rb#L27), the error seen above is due to Homebrew trying to force parallelization where it isn't wanted. We should be able to fix this by changing the formula.
