### ISSUE TITLE
[Bug] [krun] - krun fails with an uncaught exception when substrString is passed out-of-bounds indices

### ISSUE THREAD

**Issue by malturki** [runtimeverification/k#1820]
K Version
---------

```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: bfcf61f
Git branch: master
Build date: Wed Feb 17 11:11:17 CST 2021
```

Description
-----------

A call to `substrString(S, start, end)` with `start` or `end` being greater than `lengthString(S)` causes `krun` to fail at runtime with an uncaught exception.

When `start >Int lengthString(S)`, the error is:
```
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Invalid string slice
../../k/k-distribution/target/release/k/bin/krun: line 48: 91470 Abort trap: 6           "$@"
[Error] Critical: Backend crashed during rewriting with exit code 134
```

When `end >Int lengthString(S), the error is:

```
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Invalid string slice
../../k/k-distribution/target/release/k/bin/krun: line 48: 91697 Abort trap: 6           "$@"
[Error] Critical: Backend crashed during rewriting with exit code 134
```

Input Files
-----------

File: `test.k`

```
module TEST-SYNTAX
  imports STRING-SYNTAX

  syntax Pgm ::= "go"
endmodule

module TEST
  imports TEST-SYNTAX
  imports STRING

  configuration
    <k> $PGM:Pgm </k>
    <s> "test string" </s>

  rule <k> go => . </k>
       <s> S => substrString(S, lengthString(S) +Int 1, lengthString(S)) </s> // invalid! -- start index out of bounds
//       <s> S => substrString(S, 0, lengthString(S) +Int 1) </s>               // invalid! -- end index out of bounds
endmodule
     
```

File: `input.test`

```
go
```

Reproduction Steps
------------------

`kompile test.k` succeeds, but `krun` fails with:  

```
krun input.test
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Invalid string slice
../../k/k-distribution/target/release/k/bin/krun: line 48: 92713 Abort trap: 6           "$@"
[Error] Critical: Backend crashed during rewriting with exit code 134```
```

Expected Behavior
-----------------

- I don't think that this is normal behavior. I think `krun` should fail "gracefully" by catching this exception, producing an a more descriptive error message to the user, and if possible pointing out where in the file the invalid index is used. 
- This should also be documented so that users of `substrString` are reminded to guard against this problem when strings are dynamically loaded (bounds are not known a priori).

**Comment by dwightguth** [comment]
This /is/ the expected behavior. Hooks don't have a way of reporting an error aside from either aborting or throwing a c++ exception, but they're not called from a c++ function, so they can't actually be caught by anything because they don't know how to unwind the stack. In theory, llvm has functionality for catching exceptions, since clang++ compiles to llvm, but it's not very clear or well documented and it would greatly complexify the code generation process of the llvm backend. My estimate for how long this would take is probably at least 3 weeks, and for such a minor improvement in the quality of the error message, it's just not worth it. But you can debug the application in gdb, look at the stack trace, and the stack trace will point you to the exact line of code in a .k file where this function is called.

I agree having documentation of this behavior in domains.md is good though
