### ISSUE TITLE
Can you provide a Docker image (and Dockerfile)?

### ISSUE THREAD

**Issue by mssun** [runtimeverification/k#190]
It will be very nice to provide a docker image for the `k` environment. Users do not have to install dependencies on their host and this makes the running environment consistent across everyone. Thanks.

**Comment by h0nzZik** [comment]
Incidentally, I am working on that. You may use https://hub.docker.com/r/h0nzzik/kframework-fedora/tags/ until we have something official. The sources are [here](https://github.com/h0nzZik/c-semantics/tree/setup-refactor/setup/k-framework). Currently, only Java and Ocaml backends are supported in the images.

**Comment by ehildenb** [comment]
We now have several Dockerfile's in the repository (for Debian-based and Arch-based distros). Note that these dockerfiles just setup the dependencies, but do not build K (so that we can use them in CI). You can look at the steps the `Jenkinsfile` takes to build K itself once you've cloned it into the Dockerfile that is built (namely, `mvn package -DskipTests`).

Feel free  to re-open if this doesn't help.
