### ISSUE TITLE
[Bug] kprove - module not recognised

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#1915]
K Version
---------

```
$ kprove --version
K version:    5.0.0
Build date:   Tue Apr 13 17:11:09 EEST 2021
```

Description
-----------

Kprove cannot find module in file if previous module has `//` after endmodule.

Input Files
-----------

tmp.k
```
module TMP
  imports INT
endmodule
```

proof-perform-action-id-sc-call.k
```
module TRUSTED-PERFORM-ACTION-SC-CALL
  imports TMP

  claim 1 => 2
    [trusted]

endmodule//

module PROOF-PERFORM-ACTION-ID-SC-CALL
  imports TRUSTED-PERFORM-ACTION-SC-CALL
endmodule
```

Reproduction Steps
------------------

Proving the spec above fails with `[Error] Critical: Module PROOF-PERFORM-ACTION-ID-SC-CALL does not exist.`

```
$ kompile --backend haskell tmp.k && kprove --spec-module PROOF-PERFORM-ACTION-ID-SC-CALL proof-perform-action-id-sc-call.k
```

Expected Behavior
-----------------

The proof should pass.

**Comment by ehildenb** [comment]
The outer parser/tokenization process seems to not be dropping this comment correctly. Maybe it has something to do with outer-parser code which is dealing with latex comments in the past. We can likely directly drop the latex parser capabilities and maybe this will be resolved.

**Comment by radumereuta** [comment]
There is an easy fix for this, but it's going to create side effects, so I tend to label this issue as a Won'tFix.

What happens is the outer parser looks for keywords to know when to stop parsing bubbles. These keywords _must_ be surrounded by whitespace (`syntax`, `rule`, `claim`, `context` and `endmodule` - module and imports are not keywords). In this case, the claim continues to gobble input until the last `endmodule`.

There is a very simple workaround though, just ad an empty space between `endmodule` and `//` and it should parse just fine.

The side effect looks something like this:
`rule "1" => "http://somepath"`
This will no longer be possible since `//` is going to be interpreted as a comment.
