### ISSUE TITLE
Automatic insertion of definedness conditions for simplification rules

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1938]
From a thread on Slack: https://runtimeverification.slack.com/archives/CC360GUTG/p1619189886325800

The gist is, for `simplification` rules we _assume_ the user has added teh appropriate side-conditions to make sure that undefinedness is preserved by them (whereas with semantic rules we inject extra bits to force this to happen).

Given a rule `rule LHS => RHS requires C ensures E [simplification]`, we need to make sure that `\ceil(LHS)` makes it into the path condition to preserve undefinedness. You can do this by (i) making sure all function functions in `LHS` are "obviously defined" (eg. total functions), (ii) adding `\ceil(LHS)` (or something equivalent) to the `C` requires clause, or (iii) adding `\ceil(LHS)` (or something equivalent) to the `E` ensures clause.

This puts the onus on the user to write correct simplification rules, _even though_ we know that it's perfectly sound to just slap `\ceil(LHS)` on either the requires or ensures clause and enjoy the same benefits.

The reason this is not done automatically is because there is not an agreed-upon convention for whether this should go in the requires or the ensures clause. If you add it to the `requires` clause, and the backend cannot prove it, it will block the `simplification` rule from being applied, which likely will cause other simplification rules to not be able to apply, and the term will remain unsimplified (even though through a chain of simplifications we may be able to learn that it is undefined, and thus prune it). If you add it to the `ensures` clause, the backend will happily apply the rule and add the definedness condition to the path-condition, which will allow it to continue attempting simplification on the term until it learns that it is undefined, _but_ this may also lead to infinite loops if the simplification rules are not terminating.

So one proposed solution is this:

- If you can show by some metric that the RHS is smaller than the LHS (contains fewer of each symbol, fewer variables, etc..., can even look into termination theory that Maude uses), add `\ceil(LHS)` to `ensures` clause and allow the optimistic simplification.
- If you cannot show that the RHS is smaller than the LHS, add `\ceil(RHS)` to `requires` clause to force early definedness checks.
- Allow the user to override this with an attribute.

The reason to automatically insert these conditions in the first place is that it's really easy for a human to accidentally write unsound rules in the first place, even though we _know_ it's possible to prevent this.

**Comment by ttuegel** [comment]
> If you add it to the `ensures` clause, the backend will happily apply the rule and add the definedness condition to the path-condition, which will allow it to continue attempting simplification on the term until it learns that it is undefined, _but_ this may also lead to infinite loops if the simplification rules are not terminating.

This is not quite right. First, putting `\ceil(LHS)` anywhere in the rule (`requires`, `ensures`, or even `RHS`) will cause an infinite loop. So, when `LHS` has the form `f(P[1], P[2], ...)` you actually want to write `\ceil(P[1]) \and \ceil(P[2]) \and ...`. Now, you should be able to put that anywhere in the rule without causing a loop.

Second, it's actually unsound to put anything but `\top` in the `ensures` because of the way equations are encoded. The rule

``` k
rule LEFT => RIGHT requires REQUIRES ensures ENSURES
```

is translated to

``` kore
axiom \implies(REQUIRES, \and(\equals(LEFT, RIGHT), ENSURES))
```

so that if `ENSURES` is `\bottom` and `REQUIRES` is anything else, then the axiom is `axiom \bottom` which is unsound. Actually, we want to say

``` kore
axiom \implies(REQUIRES, \equals(LEFT, \and(RIGHT, ENSURES)))
```

but the distinction hasn't been important before because we really haven't had any equalities with `ensures` clauses. Note that this changes the meaning of `ensures`!

Supposing we correct two issues, then the only problem I imagine is what you pointed out: `RIGHT` may be much larger than `LEFT`, so if we put the definedness condition in `ENSURES`, we may end up doing a lot of simplification only to find that `ENSURES` is `\bottom`.

**Comment by ehildenb** [comment]
As two separate things:

- Fix the way the frontend encodes the `ensures` clause.
- Automatically inject correct defineness conditions into `ensures` clause of simplification rules.

**Comment by radumereuta** [comment]
@ehildenb do we still need this?

**Comment by ehildenb** [comment]
Yes, this is related to the recent work on simplification @radumereuta and @ana-pantilie .

**Comment by ana-pantilie** [comment]
Once we have something that can generate minimal definedness conditions for rules, we can apply it to simplification rules as well.

**Comment by ehildenb** [comment]
Closing this in favor of newer issues.
