### ISSUE TITLE
Performance regression in java serialization

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2047]
I'm making an issue so we can keep better track of the info I found. Regression starts with #2015

I ran `time make -j 32 regression-new` on my local machine and before I used to get 1m54s, now I'm getting 5m03s.
I ran `time make -j 21 regression-new` on rvwork-4 and before I used to get 3m52s, now I'm getting 7m12s.

That's kind of much. I think `kserver` got affected quite badly by this change. I also looked at the CPU usage and it's a lot lower (see image). It used to be 100% all the way. The only exception was for map-symbolic-tests-haskell, but now it seems that all definitions behave like this.
![image](https://user-images.githubusercontent.com/5113255/124135881-e5c37280-da8c-11eb-95ce-6d7962b7b8ef.png)

I ran the same tests w/o the `kserver` and I got 9m02s, vs before 7m39s, again, with less than ideal CPU utilization.

Judging by the way the CPU is being underutilized there might be a race somewhere in the serialization process.

**Comment by dwightguth** [comment]
It seems that when we were using FST, we needed a global lock because the FST serialization algorithm wasn't thread safe. However, this introduces a whole lot of lock contention because only one process could serialize at the same time, and no process could deserialize while another was serializing. Removing the lock seems to have addressed the performance issues, while still having all the tests pass both with and without kserver. I will have a PR up shortly, I'm just doing a bit more testing.

**Comment by radumereuta** [comment]
Closed by #2051

**Comment by radumereuta** [comment]
`time make -j 32 -O regression-new`
with the kserver
before: 1m53s, current: 1m47s (both are highly repeatable)
w/o the kserver
before 7m39s, current 7m42s
It seems that the performance difference is not visible. With the kserver is slightly faster. w/o the kserver is within the margin of error.
