### ISSUE TITLE
[Bug] [kompile] - uninformative message when import is missing

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/k#2145]
K Version
---------
```
$ kompile --version
K version:    5.1.146
Build date:   Wed Aug 18 23:43:23 EEST 2021
```

Description
-----------

Kompiling a definition where an import is missing can give a very uninformative message. In my particular case, the issue was that the definition was not importing the `BOOL` module.

Input Files
-----------

File: `test.k`

```
module TEST
    imports INT

    rule <k> 1 => true </k>

    syntax Bool ::= f(Int) [function]
    rule f(X) => true requires X <Int 3

endmodule
```

Reproduction Steps
------------------

```
$ kompile --backend haskell -d . test.k
[Error] Inner Parser: Parse error: unexpected token '</k>'.
        Source(/home/ana/kore/test/kframework-issue/test.k)
        Location(4,24,4,28)
[Error] Inner Parser: Parse error: unexpected token 'requires'.
        Source(/home/ana/kore/test/kframework-issue/test.k)
        Location(7,23,7,31)
[Error] Compiler: Had 2 parsing errors.

```

Expected Behavior
-----------------

The error should indicate that it cannot recognize `true` or something from the `BOOL` module, instead of pointing to issues with `</k>` or `requires`.

**Comment by dwightguth** [comment]
The problem here is that the error message you see here, while hard to understand for a human, is actually technically accurate. It would be difficult to fix this. Even if we were to do something slightly more intelligent like tell people what tokens it was expecting instead, you would just get an error like `"Unexpected token '</k>'; expected '('"`, which would still be completely misleading. We would have to somehow apply a very complicated heuristic like determining that the last token that was parsed was parsed as a klabel and then assuming that that parse was erroneous and backing up and reporting the error there. But the problem with such a complex heuristic is that if you actually did mean to write a klabel, then you would get a completely misleading error message that is even worse for having had the heuristic applied.

Practically speaking, it's a better use of our resources making sure our employees understand enough about k to be able to understand errors like this, than to try to come up with a complicated and fragile technical solution.

**Comment by ehildenb** [comment]
We could pass in a list of acceptable klabels into the parser to make this error message better?

Or could we say "if something unexpected happens right after a klabel", Should we say something like "Perhaps check the previous parsed label `true`?"

We can make it so that when we have unexpected tokens like this, we mention the previous token as well, and _suggest_ that it could be the problem. Maybe something like "near token `true`, unexpected token `</k>`"

**Comment by dwightguth** [comment]
This was essentially fixed by the change that reports the previous token in addition to the current token during a parsing error. So I'm going to close this.
