### ISSUE TITLE
Support Bytes literals in K rules

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2362]
Currently, I have to build rules like this:

```
    claim [BASIC-BLOCK-64-TO-295]: <kevm>
           <k>
             ( JUMP 802 => . )
             ~> #pc[ JUMPI ]
             ~> #execute
             ...
           </k>
           <mode>
             NORMAL
           </mode>
           <schedule>
             ISTANBUL
           </schedule>
           <ethereum>
             <evm>
               <callState>
                 <program>
                   String2Bytes( "`\x80`@R4\x80\x15a\x00\x10W`\x00\x80\xfd[P`\x046\x10a\x01\xc4W`\x005`\xe0\x1c\x80c|\xdd?\xde\x11a\x00\xf9W\x80c\xbb5x;\x11a\x00\x97W\x80c\xdcM \xfa\x11a\x00qW\x80c\xdcM \xfa\x14a\x04\xdcW\x80c\xf0Y!*\x14a\x04\xf8W\x80c\xf2N#\xeb\x14a\x05(W\
                 </program>
                 <jumpDests>
                   ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( (
                 </jumpDests>
                 <id>
                   ACCT_ID
                 </id>
                 <caller>
                   CALLER_ID
                 </caller>
                 <callData>
```

Notice the `String2Bytes` in the `<program>` cell.

But if I want to make this into a `rule`, the frontend complains because of the `String2Bytes` function symbol on the LHS of the rule.

We should allow inputing `b"..."` directly in the `<program>` cell, and it should build the correct Bytes literal automatically (by just calling `String2Bytes` on the input. _Or_, this particular case should be constant folded, so that the back just sees the bytes literal there instead of having to evaluate `String2Bytes`.

**Comment by ehildenb** [comment]
Example definition that should kompile:

```
module TEST
    imports BYTES

    configuration <k> $PGM:Bytes </k>
    
    rule <k> b"\x80\x00\x80" => b"\x80\x00" ... </k>
endmodule
```

**Comment by radumereuta** [comment]
Add new syntax to domains.md. The proposed syntax seems fine.
Handle the new token through kompile.
Make sure the backends expect the new format.

**Comment by dwightguth** [comment]
I added the syntax to the frontend and it turns out that it actually already generates the correct kore with no need for further adjustments. However, when testing Everett's example, I discovered an unrelated bug in the llvm backend that prevents the rule Everett wrote from applying. Interestingly, it also affects Strings with the same contents. It seems to affect most programs which match against raw binary data, but me simply never discovered it because we rarely match against strings containing unprintable characters. I would like to fix it before merging this code, otherwise people will not feel that bytes literals work correctly in most cases, even though the bug is technically unrelated to Bytes specifically.

I believe it will be a relatively simple fix; I expect I can have a PR into the backend ready by the end of the day tomorrow.
