### ISSUE TITLE
[Bug] [kompile] - UNSIGNED-INT-SYNTAX implicitly included in arbitrary module

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/k#2372]
K Version
---------

```
K version:    v5.2.21-17-g44ebd7036
Build date:   Tue Dec 07 10:52:28 CET 2021
```

Description
-----------

The UNSIGNED-INT-SYNTAX module seems to be implicitly included in an arbitrary module, causing errors with definitions.

Input Files
-----------
`foo1.k`
```k
module FOO1

  syntax Stuff ::= r"[0-9]+" [token]

endmodule
```

`foo2.k`
```k
module FOO2

 syntax Foo ::= r"[0-9]+" [token]

endmodule
```

Reproduction Steps
------------------
For `foo1.k`
```
kompile foo1.k
```
Output:
```
[Error] Compiler: Inconsistent token precedence detected.
	Source(/home/juan/Documents/RV/k/k-distribution/target/release/k/include/kframework/builtin/domains.md)
	Location(893,18,893,51)
[Warning] Compiler: Could not find main syntax module with name FOO1-SYNTAX in
definition.  Use --syntax-module to specify one. Using FOO1 as default.
```

For `foo2.k`
```
kompile foo2.k
```
Output:
```
[Warning] Compiler: Could not find main syntax module with name FOO2-SYNTAX in
definition.  Use --syntax-module to specify one. Using FOO2 as default.
```

Expected Behavior
-----------------
To get only the syntax module warning when running `kompile foo1.k`:
```
[Warning] Compiler: Could not find main syntax module with name FOO1-SYNTAX in
definition.  Use --syntax-module to specify one. Using FOO1 as default.
```

**Comment by radumereuta** [comment]
If the UNSIGNED-INT-SYNTAX module is included, then this is the 'expected' behavior.
So we should focus on why this module is being included.

**Comment by dwightguth** [comment]
The import chain at fault here is:

```
FOO1
DEFAULT-CONFIGURATION (implicit because your definition has no configuration declaration)
MAP (implicit because DEFAULT-CONFIGURATION has a configuration declaration)
INT-SYNTAX
UNSIGNED-INT-SYNTAX
```

Because all definitions are required to import the MAP module implicitly in this fashion, and thus in turn the UNSIGNED-INT-SYNTAX module, it is impossible currently to create a definition whose scanner does not contain that regex terminal. Thus, the expected behavior for both of these definitions is to report an error involving conflicting token precedence, and the correct workaround is to give that production the `prec(2)` attribute.

I'm not entirely sure why the inconsistent token precedence error isn't being reported by FOO2. that does sound like a bug; I will have to investigate further.
