### ISSUE TITLE
Remove now unused arguments to functions

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2418]
Given the recent deletion of the OCaml backend, we need to check for: perhaps the second argument of TreeNodesToKORE or getCombinedGrammar is no longer needed? https://github.com/runtimeverification/k/pull/2417#discussion_r792175451

**Comment by radumereuta** [comment]
I've looked over this and the only time it is false is in this [`toString`](https://github.com/runtimeverification/k/blob/master/kore/src/main/scala/org/kframework/parser/treeNodes.scala#L46)
This is important because it tells the pretty printer not to add sort annotations to variables.
We tried to make this change before and the diff was huge. Almost every single test output needed to be updated.
My take on this is to not remove the parameter, and close this issue.

**Comment by radumereuta** [comment]
Too many files will be changed by this modification.
