### ISSUE TITLE
[Bug] [krun] Paser Error with int addition and subtraction expression without spaces

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/k#2455]
K Version
---------

```
K version:    v5.2.85-0-gcba885f37-dirty
Build date:   Wed Feb 16 08:15:01 AEDT 2022
```

Description
-----------

+/- operators in INT sort didn't produce same result with/wo spaces in expressions

Input Files
-----------
File name: calc.k
```k
module CALC-SYNTAX
    imports INT
    imports BOOL

    syntax Int ::= "-" Int       [neg, function]
                 | "(" Int ")"   [bracket]
                 | Int "*" Int   [times, function] 
                 | Int "+" Int   [plus, function]
                 | Int "-" Int   [minus, function]
                 | Int "/" Int   [div, function]

    syntax priorities neg > times div > plus minus

    syntax left times
    syntax left plus
    syntax left minus
    syntax left div
endmodule

module CALC
    imports CALC-SYNTAX

    rule - I => 0 -Int I
    rule I1 + I2 => I1 +Int I2
    rule I1 - I2 => I1 -Int I2
    rule I1 * I2 => I1 *Int I2
    rule I1 / I2 => I1 /Int I2
endmodule
```

Reproduction Steps
------------------
kompile calc.k
krun -cPGM="1+2"
krun -cPGM="1-2"

Expected Behavior
-----------------

should produce 3 and -1 respectively.

**Comment by dwightguth** [comment]
This is actually the expected behavior, although I recognize that it is counterintuitive. The `INT` module defines a syntax of integers that includes an optional sign of positive or negative. Additionally, the behavior of K's lexer is that when a string is ambiguous with regards to its tokenization, the token which is longest is preferred. As a result, your program is being lexed as `"1" "+2"` rather than `"1" "+" "2"`. Thus, there is a parser error because your grammar does not permit an Int to follow another Int. You can fix this by replacing the import of `INT` in the syntax module with an import of `UNSIGNED-INT-SYNTAX`

**Comment by yanliu18** [comment]
Well, it is different to normal understanding, seems like "+2" is treated as a token? 
Do we have a better way?

Another example, for expression "1+-2" the parser tree is 
```_+__CALC-SYNTAX_Int_Int_Int`(#token("1","Int"),#token("-2","Int"))```
where "-2" is treated as a token. 

However, "-" is defined as a function both in the INT sort in the _domains.md_ and in the _calc.k_ (example above). I would expect "1+-2" parsed as 
````_+__CALC-SYNTAX_Int_Int_Int`(#token("1","Int"), ` _-__CALC-SYNTAX_Int_Int` (#token("-2","Int")))```.
