### ISSUE TITLE
[Bug] [krun] - libc++abi: terminating with uncaught exception of type std::invalid_argument: Duplicate keys

### ISSUE THREAD

**Issue by PumpkinDemo** [runtimeverification/k#2565]
K Version
---------

```
$ kompile --version
K version:    5.2.49
Build date:   Thu Dec 16 23:47:12 CST 2021
$ krun --version
K version:    5.2.49
Build date:   Thu Dec 16 23:47:12 CST 2021
```

Description
-----------
The problem is solved already.
Due to the `M => M C |-> Set` and it should be `M => M [C <- Set]`

But could there be some optimization about the error reporting mechanism？

Input Files
-----------
https://gist.github.com/PumpkinDemo/617fb189c7c6ac73760d168752e07960

Reproduction Steps
------------------
Just prepare files like the gist link and run `kompile test.k && krun base.conf.1`

Expected Behavior
-----------------
output cells after rewriting?
or some syntax/parsing errors which can tell me where is wrong

**Comment by Baltoli** [comment]
@dwightguth @theo25 This is similar to https://github.com/runtimeverification/llvm-backend/pull/505 (improving error messages for substring hook errors). We could in theory add more information to the error handler here, but it would complicate the code somewhat.

My suggestion is that we just improve the error message text, rather than adding the keys themselves to it. For example:
> std::invalid_argument: Duplicate keys when concatenating maps

or something similar.

**Comment by Baltoli** [comment]
@PumpkinDemo It's not possible to detect this error at compile or parse time; it's a fundamentally runtime error that occurs because of dynamic behaviours of your program.

To find this type of problem more easily, I recommend the [GDB integration](https://kframework.org/k-distribution/k-tutorial/1_basic/19_debugging/) we have for K.

If I run your example until it crashes, I can navigate to these stack frames:
```
#9  0x000000000033dddb in hook_MAP_concat (m1=capability |-> .Set
filesystem |-> .Set
process |-> .Set
security |-> .Set
system |-> .Set, m2=filesystem |-> SetItem ( mount )
SetItem ( remount )
SetItem ( unmount )) at /home/bruce/code/k/llvm-backend/src/main/native/llvm-backend/runtime/collections/maps.cpp:31
31	      throw std::invalid_argument("Duplicate keys");
(gdb) 
#10 0x00000000002c5bb3 in apply_rule_182 (Var'Unds'DotVar1=.Pgm ~> ., Var'Unds'Gen0=<optimised out>, 
    Var'Unds'Gen1=<optimised out>, Var'Unds'Gen6=<optimised out>, VarC=<optimised out>, VarM=<optimised out>, 
    VarPS=<optimised out>) at /home/bruce/code/scratch/test.k:60
60	    rule <k> class C:ClassName { PS:PermNames } => . ...</k>
```

You can see that the crash is in the `MAP_concat` hook, and that the two maps in question have the key `filesystem` in common. You can also see the rule that matched to produce the crash.
