### ISSUE TITLE
[KIP] - Support for symbolic sets

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/k#2612]
We need to support symbolic sets in the frontend, similar to the way we support symbolic maps. The frontend should add similar axioms to the ones added here: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L179.

This needs to be implemented in the frontend first and only then can the changes to the backend be made.

I don't know the frontend details, but this comment from `domains.md`, module `MAP-KORE-SYMBOLIC` provides some documentation on what is generated for K maps and should be generated as well for K sets:
```
/*
// The rule below is automatically generated by the frontend for every sort
// hooked to MAP.Map. It is left here to serve as documentation.

  rule #Ceil(@M:Map (@K:KItem |-> @V:KItem)) => {(@K in_keys(@M)) #Equals false} #And #Ceil(@M) #And #Ceil(@K) #And #Ceil(@V)
    [anywhere, simplification]
*/
```

So for the sorts hooked to `SET.Set`, I think the rules should look like:
```
rule #Ceil(@S:Set SetItem(@K:KItem)) => { (@K in @S) #Equals false } #And #Ceil(@S) #And #Ceil(@K) [anywhere, simplification]
```

Motivation
----------

This reasoning is currently implemented in the Haskell backend internally which is a problematic approach. Currently, it is blocking https://github.com/runtimeverification/haskell-backend/issues/2928. Also, because of it being implemented in the backend users can't provide their own simplification rules over set functions like `-Set`.

**Comment by ehildenb** [comment]
@ana-pantilie can you write down the K rules that correspond to these set-definedness conditions? You can likely infer them by inspecting the same ones generated for Map, and specializing them to sets.

This will help the implementor to know what Kore axioms to generate here.

**Comment by radumereuta** [comment]
We should update domains.md to include some simplification rules for `Set` functions similar to the ones in `MAP-KORE-SYMBOLIC`

**Comment by radumereuta** [comment]
We should also add tests for Sets similar to maps: https://github.com/runtimeverification/k/tree/master/k-distribution/tests/regression-new/map-symbolic-tests

**Comment by radumereuta** [comment]
1. ModuleToKore.java needs to be updated
2. domains.md needs to be updated to clone `module MAP-KORE-SYMBOLIC [kore,symbolic]`
3. port the test suite `regression-new/map-symbolic-tests` to work for sets.

**Comment by denis-bogdanas** [comment]
@ana-pantilie Is the Haskell backend ready for this change or we need to sync changes both in frontend and backend?

**Comment by denis-bogdanas** [comment]
@traiansf @ana-pantilie I have 2 questions related to `#Ceil` while working on this issue.
1. How are set variables used in `#Ceil` different from regular rule variables?
2. For symbolic maps, you implemented `#Ceil` rule for map constructor in front-end: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L548
From what I know this is required because sort `Map` is basically cloned for every map cell collection. Is this the only `#Ceil` rule used by map cell collections?

**Comment by denis-bogdanas** [comment]
@ana-pantilie I finished porting the test suite, but didn't implement symbolic rules yet. Almost all tests generate `#Ceil` terms. For example, this claim:
```
claim <k> union ( (SET:Set SetItem(X:MyId)) |Set SetItem(Y:MyId) |Set SetItem(Z:MyId) ) => . </k>
```
generates this output:
```
  #Ceil ( SET
  ( SetItem ( Y:MyId ) -Set SetItem ( X:MyId ) ) )
#And
  #Ceil ( SET
  SetItem ( X:MyId ) )
#And
  #Ceil ( SetItem ( X:MyId )
  ( SetItem ( Y:MyId ) -Set SetItem ( X:MyId ) ) )
#And
  <k>
    unionResult ( ( SET
    SetItem ( X:MyId )
    ( SetItem ( Y:MyId ) -Set SetItem ( X:MyId ) ) ) |Set SetItem ( Z:MyId ) ) ~> .
  </k>
```
Why are `#Ceil` terms generated here? Is this because there's still a custom symbolic sets implementation in Haskell backend? For the equivalent test for symbolic maps no `#Ceil` terms appear in the output.

**Comment by traiansf** [comment]
Short story: I don't think you really need `#Ceil` rules for sets, as their operation are always defined (but you might need to annotate those operations as functional).

But since you asked a question, let me try to answer it:

`#Ceil` side conditions are generated for all operations which are not declared to be total (I think it's the `functional` attribute).
In particular, our constructor for maps (concatenation of maps) is undefined if its arguments share keys; similarly, the map getter is undefined if the key is not present.

Therefore, esp. if performing symbolic execution, we use simplification rules for `#Ceil` to translate definedness into conditions that an SMT can check.

Set variables are crucial in defining such rules, because they can match anything (including bottom/undefined), while element variables must ensure definedness and thus would not match things which are not known to be defined.

As far as I know, the `#Ceil` generation code for maps in the frontend is needed because of the user-defined maps such as maps associated to cells, and it generates rules like the one for basic maps here
https://github.com/runtimeverification/k/blob/master/k-distribution/include/kframework/builtin/domains.md?plain=1#L447

**Comment by ana-pantilie** [comment]
> Short story: I don't think you really need #Ceil rules for sets, as their operation are always defined (but you might need to annotate those operations as functional).

@traiansf Please elaborate, I don't understand how Set operations are always defined. If I build a Set using concat, I still need to generate the definedness conditions for it.

@denis-bogdanas We discussed that the frontend can implement these changes first, because the backend needs them to function correctly on https://github.com/runtimeverification/haskell-backend/pull/3062. If you noticed any cyclic dependency between the two please let me know and we can find a different way of integrating our changes.

**Comment by denis-bogdanas** [comment]
@ana-pantilie Blocked on this issue: https://github.com/runtimeverification/haskell-backend/issues/3107

**Comment by denis-bogdanas** [comment]
Partially depends on this issue, there are workarounds: https://github.com/runtimeverification/haskell-backend/issues/3124
