### ISSUE TITLE
[Bug] [krun] - crash on missing rule

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/k#2618]
K Version
---------

```
$ kompile --version
K version:    v5.3.53-0-g3b5a40838
Build date:   Mon May 23 10:43:34 AEST 2022
```

Description
-----------

`krun` crashed on an evaluation with syntax defined but a missing reduction rule.

Input Files
-----------
File `missing-rule.k`
```
module MISSING-RULE-SYNTAX
  syntax Thing ::= "thing" [function]
endmodule

module MISSING-RULE
  imports MISSING-RULE-SYNTAX
endmodule
```
Reproduction Steps
------------------
```
$ kompile missing-rule.k
$ krun -cPGM='thing'
Lblthing'Unds'MISSING-RULE-SYNTAX'Unds'Thing{}
/home/jost/work/RV/code/k/k-distribution/bin/../lib/kframework/k-util.sh: line 85: 29521 Aborted                 (core dumped) "$@"
[Error] krun: Backend crashed during rewriting with exit code 134
```

The above file was the simplest version, other variants that produce the same "crashing" behaviour were
* `syntax Thing ::= "thing" [token]`
* `syntax Int   ::= something(Int) [function]`
(and evaluating `thing` and `something(42)`, respectively)
Whether or not there are several modules probably does not matter but that was how I discovered it (forgot an `imports`).

Expected Behavior
-----------------
Output of the term that K is stuck on (`thing` here), no report of crashing.

**Comment by Baltoli** [comment]
The problem here is in `emitGetTagForSymbolName`; if there are no rules to evaluate a function, then the backend fails to look up the internal tag for that function when constructing the initial configuration.

I think we could fix this by changing the semantics of `emitGetTagForSymbolName` to return the maximum possible tag (i.e. `std::numeric_limits<uint32_t>::max()` when lookup fails, instead of aborting the program. This would only change the behaviour of programs that use the full 4294967295 symbols.

Then, in `constructInitialConfiguration` we could look for that value and print a friendlier error message. Other existing call sites could be handled similarly.

@dwightguth @theo25 any thoughts on this? I don't think this can reasonably be handled better in the frontend; you'd need to check for _any_ possible function call stack in the initial config that could hit a stuck case.

**Comment by dwightguth** [comment]
I mean, I think we might actually use the tag 2^32-1 already for something or other, so it might need to be adjusted down one or two, but that definitely could work.

**Comment by radumereuta** [comment]
Because this error happens in the configuration construction phase we have to do something special.
The solution proposed above should be fine for now.

We should also add a front end check to look for functions with no evaluators and give an error message.
TODO: split this issue into two to track the changes to the front end and the backend.

**Comment by Baltoli** [comment]
@theo25 Is this the same as https://github.com/runtimeverification/k/issues/2446?

**Comment by theo25** [comment]
It seems so to me.

**Comment by radumereuta** [comment]
Let's make it a warning in the front end. Kompilation should go through, and the backend should give an error message depending on what makes sense there.

**Comment by radumereuta** [comment]
We already have a hidden warning for this:
```
[Warning] Compiler: Symbol 'foo(_)_CHECKUNUSEDSYMBOL_Foo_Int' defined but not used. Add the 'unused' attribute if this is intentional.
	Source(checkUnusedSymbol.k)
	Location(9,18,9,26)
	9 |	  syntax Foo ::= foo(Int)
	  .	                 ^~~~~~~~
```
Should we make it visible since it caused us so many issues? We also invented `no-evaluators` when we already had `unused`

**Comment by radumereuta** [comment]
Give a warning message for functions with `no-evaluators` in the front-end.
Make sure this can be turned off with some kind of option.

**Comment by radumereuta** [comment]
This requires too much time to get right.
I think the error message returned by the backend should suffice for now.
Please reopen if it is a problem in the future.
