### ISSUE TITLE
`comm` attribute is being ignored on llvm and Haskell backends

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2774]
- [x] change the front end - @radumereuta 
- [ ] change the Haskell Backend - @ana-pantilie 
- [ ] change the LLVM Backend - @dwightguth 

Simplification rules annotated with the `comm` attribute in the Haskell backend are being [ignored](https://github.com/runtimeverification/haskell-backend/blob/b06757e252ee01fdd5ab8f07de2910711997d845/kore/src/Kore/Equation/Registry.hs#L125-L142)
Likely the LLVM backend does the same.

This is an issue because of https://github.com/runtimeverification/k/pull/2754
As a workaround, we removed the `comm` attribute when we generated those rules.

This needs to be investigated by the Haskell and the LLVM teams. @ana-pantilie @theo25

**Comment by dwightguth** [comment]
I mean, if we wanted to we could probably just not emit those axioms in the frontend since they are not, as I said, being used. I believe the original intent was for them to be used during proof object generation, but that's a good ways away from being at all relevant.

Alternately, we could just give the old use of the comm attribute a different name, like `commutativity` or something.

**Comment by radumereuta** [comment]
Right now the front end generates only two of those axioms: for `_Set_` and for `_Map_`, but as you say, if they're not being used, we could use a different keyword and disable this code path. But let's see how this PR behaves further.

**Comment by radumereuta** [comment]
We should try to use `commutativity` as Dwight suggested and change the front end and the backends together so we don't miss functionality. We should try to keep the `comm` attribute on the new productions and simplification rules.

@dwightguth please point out where in the LLVM backend we need to make changes.

**Comment by dwightguth** [comment]
LLVM backend needs to be changed in two places:

* https://github.com/runtimeverification/llvm-backend/blob/master/matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala#L141
* https://github.com/runtimeverification/llvm-backend/blob/master/lib/ast/AST.cpp#L1185

This is not a hard change; I would suggest whoever is working on the frontend also do the backends.

@ana-pantilie I suggest sharing where in the Haskell backend this happens also.

**Comment by ana-pantilie** [comment]
The backend should parse the `Comm` attribute as true for both `"comm"` and the new version (`"commutativity"`?) here: https://github.com/runtimeverification/haskell-backend/blob/e0580ec3a1ecfb05b0e8e2730cc16c9adfd6a6f5/kore/src/Kore/Attribute/Comm.hs#L50. After the frontend is changed, the attribute should be renamed to `Commutativity` instead.

**Comment by dwightguth** [comment]
This feels like the wrong solution to me. If we're not using these axioms currently, let's just not emit them. We can always add them back easily enough if we get to a point where we actually need them. But following a complicated migration path just to deal with code we're not actually using at all just feels like a waste of our time to me.

**Comment by ana-pantilie** [comment]
I did a bit of investigating, and I think the Haskell backend only uses the old `comm` attribute to know that it has to _ignore_ those axioms which are marked as `comm`.

I can't remember, did we want the new `comm` for symbols to be sent to the backends as well? If not, then it's as simple as, when the frontend stops emitting those `comm` axioms we can just delete the `comm` attribute from the backend.

**Comment by dwightguth** [comment]
Here is, I believe, the complete plan of attack:

1. Modify the frontend so it no longer emits the commutativity axioms that are getting ignored by both backends anyway.
2. Modify both backends so they no longer ignore axioms with the comm attribute (once the first step is merged). The haskell backend can just start treating the comm attribute like any other attribute it doesn't care about.
3. Modify the frontend so that we don't strip the comm attribute from axioms on which it is placed anymore.

That's it.

**Comment by dwightguth** [comment]
I will get started on this today and I believe I can complete all 3 steps.

**Comment by ana-pantilie** [comment]
If someone picks this up, ping me.

**Comment by dwightguth** [comment]
Step 1 of my work plan is complete. Someone still needs to do steps 2 and 3.
