### ISSUE TITLE
[kprove] Control which claims the backend discharges

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2812]
On the CLI, we'd like to be able to dynamically mark claims as trusted, or to exclude them. This could come in 3 forms (I think we could have uses for all 3):

- `--trusted CLAIM_ID_LIST`: Mark this set of claims as trusted.
- `--exclude CLAIM_ID_LIST`: Remove these claims from the definition before sending to backend.
- `--claims CLAIM_ID_LIST`: Only keep the named claims in the definition before sending to the backend (remove the others).

This allows us to select subsets of claims to discharge with different calls to the prover, instead of having to discharge them all at the same time. Currently, for the Foundry project, we are automatically generating 1 K-claim per foundry test, which means there will be at least hundreds of claims. For testing, it's a lot easier if we can say which claims we actually care about running for that run. For this, only the third flag `--claims` is needed. The other two are variants I thought others may find useful.

**Comment by radumereuta** [comment]
- what happens if you pass to kprove a module that is empty (no claims)
  - should not crash
  - if the claim list is empty, we should do the same thing as right now
- report an error if the claim doesn't exist
- report an error if the claim list is empty when specifying `--claims` or other options

CLAIM_ID_LIST example: ModuleName.claim_name, separated by commas
