### ISSUE TITLE
Reduce memory usage of kompilation

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2866]
@sskeirik reports that memory usage is a bottleneck / issue for the project he is working on, and asks if there is any way to reduce it.

**Comment by Baltoli** [comment]
@sskeirik Please get us a minimal working example so we can investigate this properly.

**Comment by radumereuta** [comment]
This really needs more details.
It's possible this is because of parsing, so I would like to know:
- which semantics is this?
- output of `kompile -v`
- the output of 'kompile --profile-rule-parsing <file>` could help. Rules that take a long time to parse may produce many ambiguities. Parentheses or sort annotations could help a lot.

It's less likely this can be minimized since such issues arise from having lots of productions and sorts. So a working branch and instructions on how I can test it are also helpful.

**Comment by dwightguth** [comment]
It's impossible to work on this without at the minimum either a self contained example, or an hprof heap dump. If you want to do the latter, you can enable the `-XX:+HeapDumpOnOutOfMemoryError` JVM flag and decrease the jvm heap just enough that it OOMs, but not so much that the heap profile will be unrepresentative of the true problem. This file is going to be several gigabytes though so you won't be able to transfer it via GitHub. You'll have to upload it to an rv server somehow and then get the person fixing the bug to transfer it.

**Comment by sskeirik** [comment]
I've been working on getting an example.

I can consistently repro the memory usage (~15GB) used during a single K semantics compilation on my machine.

Please see this issue for instructions on how to repro:

https://github.com/runtimeverification/algorand-sc-semantics/issues/741

Link used because repo is private and to avoid releasing more details publicly.

**Comment by dwightguth** [comment]
Yeah I strongly suggest you just create a heap dump yourself. Nobody wants to have to build Algorand from source to reproduce things.

**Comment by dwightguth** [comment]
Bear in mind though that the heap dump will contain private data and shouldn't be uploaded publicly.

**Comment by sskeirik** [comment]
After a bit of profiling, the algorand-sc-semantics type semantics, @radumereuta and I found that:

-   the entire kompilation process is using up to 15 GB memory
-   parsing is around 30 seconds (not too bad) and using up to 6 GB memory
-   the slowest rule took 600ms for parsing and 3s for type-inferencing
-   the high memory usage is only observed when building the LLVM backend
-   in particular, we are seeing:
    
    1.   the `java` process, during the entire LLVM backend compilation process, consistently consumes about 10 GB memory
    2.   on top of that, the `llc` phase of the LLVM backend compilation consumes around 5 GB memory

To be clear, the issue is that most client computers only have 16 GB of RAM and thus struggle to successfully build the semantics --- I have heard reports of builds taking up to an hour or just getting killed by the OOM process reaper. On my machine with 64 GB of RAM, builds finish in 3-4 minutes.

Just FYI @dwightguth and @theo25. Any thoughts on this would be appreciated. I am happy to still get that memory dump, if that is needed? Is is possible or useful to get one from `llc`?

**Comment by ehildenb** [comment]
We need to find out how the Java process is using 10GB, it seems that it's our biggest consumer.

Some quick experiments you can run @sskeirik:

- Instruct it to run 1 thread at a time the decision tree generation (modify the code here by just removing the `par`: https://github.com/runtimeverification/llvm-backend/blob/e6dc37ae64379e06493cddd2e02d1e05376c821a/matching/src/main/scala/org/kframework/backend/llvm/matching/Matching.scala#L58). If this reduced memory usage to acceptable levels, then we can add a flag for controlling that `par`.
- Running a java heap dump: some ideas: https://www.baeldung.com/java-heap-dump-capture

**Comment by radumereuta** [comment]
We spent a bit more time trying to debug this, and we couldn't make it crash with OOM.
We've removed the parallelism and we couldn't see any difference.
We've reduced the java heap memory down to 5GB (from 16GB), but kompile went through fine w/o any errors or time difference.

I've made a PR that prints out more detailed information about the kompile stages related to the backend.
https://github.com/runtimeverification/k/pull/2902

**Comment by sskeirik** [comment]
So, @radumereuta and I did some more investigation today.

Firstly, we commented out the parallel execution by commenting out the `par` expressions in the Scala code but saw no real change in memory usage.

We then tried @dwightguth's approach (using `-XX:+HeapDumpOnOutOfMemoryError` and `-Xmx`) to get a heap dump. We successively lowered the JVM max heap size to just 5GB and the compilation process still succeeded --- this really surprised me.

It makes me wonder if:

-   the JVM takes a lazy approach to GC and only attempts to aggressively garbage collect when it is using most or all of its maximum available heap
-   the JVM GC policy does _not_ take into the overall system memory usage
-   by giving the JVM more memory via the `-Xmx` option, we actually cause the JVM to use essentially all available memory on lower memory system, forcing the OS to start using swap, and making the entire compilation process _even slower_ than with a lower `-Xmx` option

I will keep looking into this; if anyone else has other thoughts, I'd love to hear them.

**Comment by ehildenb** [comment]
@sskeirik we should close this unless you can provide exact reproduction steps. It seems that it's solved by adding `-Xmx 5G` to the arguments? Does that work for the Algorand folks too? Is that still too much memory?

If it's too much memory, then we need exact reproduction steps, so that others can try this out.

**Comment by dwightguth** [comment]
I agree that the jvm is not super great at not using all available memory instead of doing garbage collection. It sounds like that's part of what is going on here. Some jvm garbage collectors are more aggressive than the one we are currently using at making sure that memory isn't taken from the os unnecessarily. It's possible you might have more luck with some jvm flags to use a different gc algorithm.

Regardless, in the absence of a heap dump or steps that reproduce problematic behavior, there's not really much actionable here.

**Comment by radumereuta** [comment]
@sskeirik can you give us an update on this?
Has the reduced memory for Java heap solved the issue for your clients?

**Comment by Baltoli** [comment]
Closing as this is over a year old and this project is no longer active; if it crops up again we can reopen.
