### ISSUE TITLE
Unary + has higher precedence over binary + when both are applicable

### ISSUE THREAD

**Issue by KPJoshi** [runtimeverification/k#31]
Version: Nightly build of K framework at commit babeea3

Consider [lesson 8](https://github.com/kframework/k5/blob/master/k-distribution/tutorial/1_k/1_lambda/lesson_8/lambda.k) of the `lambda` tutorial. Here are two simple programs:

* `1 + 2`
* `1+2`

The first gives the expected result `3`. The second gives the unexpected result `1 2`. This might to be due to the second `+` being interpreted as a unary `+` operating on the `2`. In the definition, `Exp Exp` and `Exp "+" Exp` are both valid.

This problem is not seen with `imp`. Both of the above inputs give the expected result `3`. This might be due to only `Exp "+" Exp` being present in `imp`.

Rearranging the two conflicting definitions in `lambda` and/or giving one of them higher precedence does not seem to make any difference.

**Comment by dwightguth** [comment]
This is a known issue with the K parser where we have an ambiguous tokenization of the input string. Specifically, we can scan the substring `+2` as both `"+2"`, an Int, and `"+" "2"`, a partial derivation of Exp. Currently our scanner is not capable of reasoning about ambiguities, which means that the tokenization which contains a shorter input string is silently dropped (as is the unconfigurable behavior of the scanner we are using), even though we in fact want to keep both scans and report an ambiguity to the user. There are two workarounds: you can either create a syntax module in your definition, as IMP does, which imports `DOMAINS-SYNTAX` instead of `DOMAINS`, or you can add spaces to your input strings when doing parsing.

We plan to fix this issue in the K tutorial eventually, as it is on our roadmap for the parser, but unfortunately it would require a serious structural overhaul and will probably not be ready for several months. Sorry for the inconvenience.

**Comment by radumereuta** [comment]
@dwightguth should we close this as a not planned? Scanner based parsers are always going to have this issue.

**Comment by radumereuta** [comment]
There are workarounds by structuring the syntax differently, but there isn't much we can do implementation wise.
