### ISSUE TITLE
[K-Bug] `krun --search-final` does not work with source locations.

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#3189]
### What component is the issue in?

Front-End

### Which command

- [ ] kompile
- [ ] kast
- [X] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

v5.5.88

### Operating System

Linux

### Steps to Reproduce

Run the following commands:

```
+ cat test.k
// k-distribution/tests/regression-new/locations/test.k

module TEST-SYNTAX
  imports UNSIGNED-INT-SYNTAX
  syntax Exp [locations]
  syntax Exp ::= Exp "+" Exp | Int [klabel(IntConst)]
endmodule

module TEST
  imports TEST-SYNTAX
  imports K-LOCATIONS

  syntax Location ::= Loc(Exp, String, Int, Int, Int, Int)
  rule #location(E:Exp, File, L1, C1, L2, C2) => Loc(E, File, L1, C1, L2, C2)
endmodule
+ cat input
1  + 1
+ kompile --enable-search --backend llvm --gen-bison-parser test.k
+ krun --search-final input
Created bug report: kore-match-disjunction.tar.gz
[Error] krun: kore-match-disjunction ./test-kompiled/definition.kore --module
TEST --disjunction
.krun-2023-02-24-16-49-35-iem8sQL8lv/tmp.disjunction.x8w5urp5k9 --match
.krun-2023-02-24-16-49-35-iem8sQL8lv/tmp.pattern.HFggBpi4YO --output
.krun-2023-02-24-16-49-35-iem8sQL8lv/result.kore
```

### Expected Results

The program should not crash.

**Comment by dwightguth** [comment]
The problem here is that we rely on the Haskell backend to implement search patterns, but the Haskell backend does not support the `K-LOCATIONS` module. Adding such support would be quite difficult, but fortunately, in this case such support is not actually needed. Since the user didn't explicitly pass the --pattern flag, what we can do is provide a way on the command line to skip the call to kore-match-disjunction, which is not going to have an appreciable impact on the resulting configuration, except that it will be formatted slightly differently.

Essentially, the solution is to add a flag to krun, call it --no-pattern. The flag should be an error if specified together with --pattern. The effect of the flag is nothing, unless --search or --search-final is passed, in which case we skip the invocation of kore-match-disjunction and directly use the output of the llvm backend interpreter as input to the unparser.

It should be a completely self contained change within the krun script. I think this is a good early issue for anyone who doesn't yet have familiarity with that script or the other complex bash scripts in frontend repo.
