### ISSUE TITLE
Incorrect code generated when redeclaring sort predicate

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3329]
This definition crashes the LLVM code generator by generating invalid LLVM somehow, related to the spurious redeclaration of `isNonAddr`.

I think this should maybe be caught in the frontend - when is it valid to define your own `isSort` predicates?

```k
module TYPEASSERTION
    imports BOOL-SYNTAX
    imports BASIC-K

    syntax Bool ::= isNonAddr(KItem) [function]
    syntax NonAddr ::= nonAddr(KItem)
endmodule
```

**Comment by radumereuta** [comment]
Right now we're generating [syntax ](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/compile/GenerateSortPredicateSyntax.java#L36)and [rules](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/compile/GenerateSortPredicateRules.java#L60) for sort predicates:
```
syntax Bool ::= "isExp" "(" K ")" [function, predicate(Exp), total]
rule isExp(Exp)=>#token("true","Bool") requires #token("true","Bool") ensures #token("true","Bool")
rule isExp(K)=>#token("false","Bool") requires #token("true","Bool") ensures #token("true","Bool") [owise]
```

There is also a bunch of dead code in those files.
Note that they don't appear in `compiled.txt` because those steps are [not called](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java#L100) in the main pipeline for some reason.
We should at least fix that!

**Comment by Baltoli** [comment]
Yep, I definitely agree this should go in the main pipeline. It would have helped the user who reported this in #k-public if we'd been able to look there.

**Comment by ehildenb** [comment]
It should be an error to do both of:

- Declare a sort `syntax S`
- Declare a symbol `syntax Bool ::= isS ( _ )`.
