### ISSUE TITLE
llvm-backend-matching fails to parse axiom with `\right-assoc`

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/k#3640]
Using K framework 6.0.94 (but also 6.0.92 and the llvm-backend master at the time of writing), I encounter the following error when trying to generate the jump table (`./dt` directory) with `llvm-backend-matching`:

```
$ llvm-backend-matching ./definition.kore qbaL ./fubar 0
Exception in thread "main" org.kframework.parser.kore.parser.ParseError: ERROR: Line 13256: Column 13: Expected \top,\bottom,\and,\or,\implies,\iff,\exists,\forall,\ceil,\floor,\equals,\mem, but '\ri'
  axiom{} \right-assoc{}(\or{SortTxGasPriceCell{}} (\exists{SortTxGasPriceCell{}} (X0:SortInt{}, Lbl'-LT-'txGasPrice'-GT-'{}(X0:SortInt{})), \bottom{SortTxGasPriceCell{}}())) [constructor{}()] // no junk
            ^
	at org.kframework.parser.kore.parser.TextToKore.error(TextToKore.scala:774)
	at org.kframework.parser.kore.parser.TextToKore.parsePattern(TextToKore.scala:529)
	at org.kframework.parser.kore.parser.TextToKore.parseDeclarations(TextToKore.scala:284)
	at org.kframework.parser.kore.parser.TextToKore.parseModule(TextToKore.scala:161)
	at org.kframework.parser.kore.parser.TextToKore.parseModules(TextToKore.scala:173)
	at org.kframework.parser.kore.parser.TextToKore.parseDefinition(TextToKore.scala:135)
	at org.kframework.parser.kore.parser.TextToKore.parse(TextToKore.scala:72)
	at org.kframework.parser.kore.parser.TextToKore.parse(TextToKore.scala:52)
	at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:14)
	at org.kframework.backend.llvm.matching.Matching$.main(Matching.scala:106)
	at org.kframework.backend.llvm.matching.Matching.main(Matching.scala)
```
The `definition.kore` file in this run was produced by `kompile` of the same version of K, in a command `kompile --llvm-kompile-type c ...` compiling an evm-semantics proof module. I then tested this with a stand-alone K definition (the well-known `imp.k`) and got the same result.

To reproduce:

```
$ kup install k.openssl.procps
$ kompile --llvm-kompile-type c some-definition.k
$ llvm-backend-matching some-definition-kompiled/definition.kore qbal ./fubar 0
```

What puzzles me is that the line numbers in the stack trace above do not match the code on master (or on the tagged version 6.0.94) at all. The code on master has [a `TextToKore::parsePattern()` with a case for `\right-assoc`](https://github.com/runtimeverification/k/blob/master/kore/src/main/scala/org/kframework/parser/kore/parser/TextToKore.scala#L560-L561), and [the error call is on line 621, not 774](https://github.com/runtimeverification/k/blob/master/kore/src/main/scala/org/kframework/parser/kore/parser/TextToKore.scala#L621).

**Comment by radumereuta** [comment]
@gtrepta you recently looked at TextToKore. Can you investigate this one as well?

**Comment by gtrepta** [comment]
### Alternative reproduction

(in the llvm-backend repository):
```
llvm-backend/matching$ mvn exec:java -Dexec.args="/path/to/definition.kore qbal ./fubar 0"
```

### The problem

- The decision tree generator is implemented in scala and exists in the llvm-backend
- The generator needs TextToKore from K upstream

When normally building the K distribution, this isn't an issue, because it's done in the K repository and the dt generator gets brought up from the llvm-backend submodule.

But when building the dt generator in the llvm-backend module alone, it uses a maven artifact to retrieve its dependencies on K. These appear to be from July 2020, before the parsing of left/right-assoc were implemented.

This `llvm-backend-matching` tool must be getting built in the llvm-backend module alone, which means its TextToKore implementation is out of date.

### Solution

~~We probably just need to update the maven artifact.~~

**Comment by radumereuta** [comment]
The nix package command needs to use the exact same classpath as the kompile command.
Otherwise, you will run into issues.

**Comment by gtrepta** [comment]
@goodlyrottenapple ~~Your input here would be helpful. Should `llvm-kompile-matching` be built in the K repo instead of llvm-backend, or does there just need to be an option passed to java when launching it to point it towards the same java classes that the rest of the K tools use?~~

**Comment by ehildenb** [comment]
Some questions:

- If the llvm backned depends on frontend, should we be auto-updating the dependency in the LLVM backend with a job? We'd have to make sure to not merge it too frequently, or we get a useless cycle of PRs (LLVM -> K -> LLVM -> K ...).
- `llvm-backend-matching` tool isn't a part of the K distribution currently. We could add it to the K distribution, so that it's available for K installs. I guess this would mean moving `llvm-backend-matching` from LLVM backend repo to K? Not sure.
- Do we actually need this binary/library for Haskell backend booster? We are just calling `kompile --backend llvm --llvm-kompile-type c ...` to get the shared library, so why do we need this nixified llvm-backend-matching directly?

**Comment by ehildenb** [comment]
I guess the purpose here was to be able to make reproducible bug reports, with minimal footprint. To do that, we need `definition.kore` from both backends, and then `llvm-backend-matching` is used to produce the `dt` folder from th eLLVM `definition.kore`. Instead of assuming that we have `llvm-backend-matching` available to haskell booster CI for testing, it can just assume that we have an entire K, and we also add `llvm-backend-matching` to the K distribution. Then we don't need this back dependency from K -> llvm-backend. Does that work?

**Comment by geo2a** [comment]
Here's an example of where `llvm-backend-matching` is used: https://github.com/runtimeverification/hs-backend-booster/blob/main/test/rpc-integration/resources/foundry-bug-report.tar.gz.kompile --- we're building `interpreter.so` to run a Kontrol bug report.

**Comment by gtrepta** [comment]
@geo2a @jberthold As of K Release v6.0.118, there is now a command line tool called `llvm-kompile-matching` which exposes the same functionality as `llvm-backend-matching`, but should properly parse `\right-assoc` terms. Can you please test this to see if it fixes this issue?

**Comment by radumereuta** [comment]
This might be fixed when we deployed new releases to Cloudrepo.
@jberthold when you come back can you confirm if this is still an issue?

**Comment by jberthold** [comment]
When I ran the `llvm-kompile-matching` (K version `6.0.145`) on an older `definition.kore` file, it failed to parse `\right-assoc(\or(...))` with the error message `Expected <Identifier>, but '\'`. This is due to latest changes that actually _remove_ the `\right-assoc` usage from the front-end.
Using the procedure above to reproduce (running `llvm-kompile-matching` on a freshly-compiled `definition.kore` produced by `kompile` of the same K version), the new tool works as expected (producing the matching data for `llvm-kompile`). The `definition.kore` [compiled by the new version does not contain _any_ `\right-assoc` constructs](https://github.com/runtimeverification/k/pull/3679), so this issue may have become obsolete anyway.

**Comment by Baltoli** [comment]
Going to close this issue in that case; feel free to reopen if needed.
