### ISSUE TITLE
Add kast option to show the list of tokens after scanner

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#3647]
It's hard to debug why things don't parse.
It would be useful to have an option for `kast` to show you the list of the tokens after parsing.
I think this can be done in ParsingInModule. Instead of calling the parser, just call the scanner, pretty print and exit.
The output should include:
- matched token
- location
- production used
Probably json output would be best for this. Although a simple list would work as well.
The production should contain the location information as well.

This would have been useful when debugging the mir semantics a few days ago.
@dkcumming do you have more suggestions that would help you with debugging?

**Comment by Robertorosmaninho** [comment]
Can you provide any small example definition + token you expect to match and a simple output example?

**Comment by radumereuta** [comment]
We need to have access to the tokenizer info.
On top of that we need the lines and columns. We could move that logic directly into the scanner.

**Comment by dkcumming** [comment]
Your summary is great. Just getting feedback from the lexer on what it successfully matched and it's IR would make the development process easier.

**Comment by dwightguth** [comment]
Hi, you mentioned in the PR asssociated with this issue that you liked what was provided but were hoping to also see a little bit more insight into the structure of nonterminals within strings that are being parsed.

I'm going to assume you are talking specifically about wanting to see that structure with respect to sentences that don't parse, so I'm going to propose two possible features that we could add that might help get at this somewhat, and I'd like your input on which of these two (or both) seem useful to you.

1. We could modify the error provided when parsing fails to provide information about the set of non-terminals and terminals that were allowed to appear at the point where parsing failed, as well as the productions associated with them.
2. We could modify the error provided when parsing fails to provide a partial parse tree representing the structure of the terminals that have been parsed up to that point. There would potentially be more than one, because parsing is somewhat ambiguous at this stage.

Do either or both of these ideas sound like they would be valuable to you in solving the problems you are currently facing?

**Comment by dkcumming** [comment]
Both could certainly be useful, and I think that option 2. would be preferable to me if it were output requesting verbose erroring. The error messages that happen now have been sufficient for other projects and I haven't had any problem with them. Now I might not be understanding 1. and 2. correctly, but I feel that if I have this output I may be looking at the set of permissible next steps, and looking through the syntax trying to infer what matched previously.

The problem I run into is KMIR syntax is not implemented in a robust way where when an incorrect match happens it is intuitive to figure out the trace of how the lexer got there. I'll give a quick scenario to illustrate, `IdentifierToken` ( `IdentifierToken ::= r"[_a-zA-Z][_a-zA-Z0-9]*" [token]`) appears in many places in the syntax where really it should of been a particular set of permissible keywords (which we are trying to fix now). When changing the syntax, a peculiar or unexpected production has sometimes matches containing `IdentifierToken`. The current output Radu implemented will confirm how much of the input has been matched to `r"[_a-zA-Z][_a-zA-Z0-9]*"` which is helpful, and you can see what the tokens previously matched also - and probably often this is sufficient to figure out what is going on. But there will be cases where it is still not clear, in this case seeing the tree/non-terminals that got to that those terminals would be helpful as you can identify which production is matching spuriously.

**Comment by dwightguth** [comment]
Hi. I created a new issue linked to this one that we have put into triage. We will track the proposed idea you selected there.
