### ISSUE TITLE
Master branch performance tests failing with `list index out of range`

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3738]
Example run here: https://github.com/runtimeverification/k/actions/runs/6574325069/job/17859140370

```
Exporting last bencher report from _update-deps/runtimeverification/llvm-backend to develop
Found 0 reports for k-framework in _update-deps/runtimeverification/llvm-backend
Traceback (most recent call last):
  File "/opt/workspace/./k-distribution/tests/profiling/post_results_to_develop.py", line 61, in <module>
    item = k_framework[i]
IndexError: list index out of range
```

**Comment by Baltoli** [comment]
@Robertorosmaninho you seem to be the last person to work on this - any idea what's happening?

**Comment by Robertorosmaninho** [comment]
Yeah, the list of reports is organized by pages of 255 reports each, and we're currently just looking up for the first page. Sometimes, it can happen that the reports that we want to publish are already too old. New versions of `Bencher` already provide a new command line feature to search by reports per branch instead of looking for all reports for all branches on the project. 

From the top of my head, the fix should be straightforward:
- Modify the script/workflow file to download the new version of Bencher
- Modify the `bencher reports` command on the script to use the new flags to filter the current branch
- This should be done for the workflow that publishes the `develop` branch and on the `test-pr.yml`

From the maintainer of the tool:
"These options should help and are now available in the CLI and via the API:
```
      --branch <BRANCH>
          Branch slug or UUID

      --testbed <TESTBED>
          Testbed slug or UUID

      --start-time <START_TIME>
          Start time (seconds since epoch)

      --end-time <END_TIME>
          End time (seconds since epoch)

      --sort <SORT>
          What to sort results by

          Possible values:
          - date_time: Date time of the report

      --direction <DIRECTION>
          The direction to sort the results by

          Possible values:
          - asc:  Ascending
          - desc: Descending

      --per-page <PER_PAGE>
          The number of results per page (default 8 max 255)

      --page <PAGE>
          Page number of the results to fetch
 ```
