### ISSUE TITLE
maybe link to this Windows install walk-through

### ISSUE THREAD

**Issue by DustinWehr** [runtimeverification/k#389]
This is for installing K starting with a fresh Windows Subsystem for Linux install. Written April 2019 in/for Windows 10 Pro 64-bit. I'm a modern-Windows newb , and I wrote this for people who are as prone to installation frustration as I am. 

Install the Ubuntu package from the Windows Store, which as of now is an alias for the Ubuntu LTS 18.04 package. 
I downloaded kframework_5.0.0_amd64_bionic.deb to C:\linux.
From the windows command prompt:
`ubuntu`
It'll take a few minutes to install, then you'll make a user account, and then you're in a linux shell.
You need to download package source data before you can install anything. I first tried
`sudo apt update`
but that reported a couple errors, so I tried again with
`sudo apt-get update`
and that completed with no errors. Lastly:
`sudo apt-get install /mnt/c/linux/kframework_5.0.0_amd64_bionic.deb`

That installed 1.4GB of dependencies, some of which is basic dev stuff, since it's a fresh ubuntu install, and took a long time for me. It also, apparently, compiles OCaml. 

Some instructions beginning with `1. To configure OPAM in the current shell session` showed up during the installation, and I've ignored them for now. There was also a worrying part where OPAM asked if it could modify ~/.profile and ~/.ocamlinit, and apt-get apparently answered no for me. I haven't done anything about that.

I ended up with a k installation at /usr/lib/kframework with everything owned by root, so I did:
`sudo chown -R dustin:dustin /usr/lib/kframework`

I added `export PATH=$PATH:/usr/lib/kframework/bin` to my ~/.bashrc. That was enough for the test suggested in K's INSTALL.md to work:
`source ~/.bashrc`
`make /usr/lib/kframework/tutorial/2_languages/1_simple/1_untyped/`
`krun make /usr/lib/kframework/tutorial/2_languages/1_simple/1_untyped/tests/diverse/factorial.simple`

**Comment by dwightguth** [comment]
You don't actually need to add anything to your path. It creates scripts that invoke everything in /usr/bin, like a normal ubuntu package. There are a few obscure scripts we don't create links for, but none of them are commonly used. If you end up needing them, you can update the path like you said.

K also works just fine with everything owned by root, and you can just copy the tutorial directory into your home directory and build everything with make or kompile.

As far as the ocaml messages in the terminal, you can ignore them. Ocaml is difficult to distribute, so we did the expedient thing and built it in a postinstall hook. But everything gets localized to /usr/lib/kframework/lib/opamroot and does not at all touch any other installation of ocaml you have on the machine. That's why we don't bother trying to setup ocaml for the user. The ocaml backend is going to be deprecated eventually when the llvm backend becomes production ready, so we didn't make it a priority to perfect the packaging process. Patches to make dpkg-buildpackage build ocaml and distribute it instead of building it at install time are welcome though (although you should be warned that it's going to be a huge hassle to get working).

If you want to get your instructions included in the repo, I'd suggest making a pull request so that we can go through the review process.

**Comment by DustinWehr** [comment]
> If you want to get your instructions included in the repo, I'd suggest making a pull request so that we can go through the review process.

that was the limit of my caring

**Comment by DustinWehr** [comment]
Thanks for your feedback @dwightguth. I think others getting started would want to read it, so consider linking to it!

**Comment by DustinWehr** [comment]
@dwightguth Or just add "installing on window is easy too", because it was, but the documentation makes it sound like it'll be a pain. And using WSL is pleasant. I probably wouldn't switch to a native windows client if one was released. 
Still not sure what to expect trying to install on OSX, so I haven't tried.

**Comment by ehildenb** [comment]
@DustinWehr we had one of our engineers make a PR for it, could you take a look? https://github.com/kframework/k/pull/392

**Comment by denis-bogdanas** [comment]
@DustinWehr Thanks for the guide. We are in the process of integrating it to `README`.
