### ISSUE TITLE
Questions regarding symbol overloading

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3966]
The [K User Manual](https://github.com/runtimeverification/k/blob/5fdec964181fec112631968bb32c3f187eac967e/docs/user_manual.md?plain=1#L324) hints on the possibility of overloading symbols:

> If we need to reference a certain syntax production externally, we have to manually define the klabels using the `klabel` attribute. One example of where you would want to do this is to (...) **enable overloading of a given symbol**.

> In general, it's recommended to use the `symbol` attribute whenever you use `klabel` unless you explicitly have a reason not to (eg. **you want to overload symbols**, or you're using a deprecated backend).

Accordingly, in `ModuleToKORE`, the set of overloading productions is computed:

https://github.com/runtimeverification/k/blob/5fdec964181fec112631968bb32c3f187eac967e/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L240

based on the poset of overloading productions:

https://github.com/runtimeverification/k/blob/5fdec964181fec112631968bb32c3f187eac967e/kore/src/main/scala/org/kframework/definition/outer.scala#L72

If I understand correctly, this essentially defines `p1 < p2` as:

1. `p1 != p2`
2. `p1` and `p2` have the same `klabel` attribute
3. `p1` and `p2` have the same positive number of nonterminals
4. `p1.sort <= p2.sort`
5. For every nonterminal index `i`, `p1.nonterminal[i].sort <= p2.nonterminal[i].sort`

Then to each production that is an overload of some other production w.r.t. this definition the `anywhere` attribute is attached. Another way this attribute can appear on a production is if the corresponding symbol is rewritten by a rule with the attribute.

 In the resulting KORE, both original and overloaded symbols are present. The `anywhere` attribute appears on KORE symbol declarations corresponding to overloading productions.

## Questions

1. How does overloading work from the user's perspective? Is it a parser feature? Should we document it?
2. Currently nothing stops the user from accidentally overloading a production (by reusing a `klabel` they are not aware of). Should we add an attribute to enable the user to signal purpose of overloading?
3. The user manual claims that the user "can use the provided `klabel` to refer to that symbol anywhere in the frontend K code". Overloading seems to interfere with this use case. Also, a production that either overloads or is overloaded cannot also have `symbol` (since uniqueness there is enforced). So effectively, `symbol` also means "cannot overload". Should we introduce a dedicated attribute for overloading, and enforce uniqueness of `klabel` as well?
4. In condition (4) of overloading, shouldn't the relation be the other way?
5. Why is attaching the `anywhere` attribute to overloading productions necessary? It seems to be used by the Haskell backend: https://github.com/runtimeverification/k/issues/3946#issuecomment-1930372019.

**Comment by Baltoli** [comment]
https://github.com/runtimeverification/haskell-backend/issues/3796

**Comment by Scott-Guest** [comment]
This is quite a ways down the line, but I've been thinking about long-term improvements to K's type system while working on inference, and the proposed system would pretty naturally subsume common cases of overloading.

Explicitly, if we
- #3848 
- Support parametric functions 
- Support parametric sorts
- Add built-in sorts `Join{A, B}` and `Meet{A, B}` which yield a sub-sorting lattice as described in https://github.com/runtimeverification/k/blob/5fdec964181fec112631968bb32c3f187eac967e/docs/developers/sort_inference.md

then many (possibly all?) of K's function overloading can just be typed directly as one symbol rather than using separate overloaded symbols. 

Instead of overloading
```
syntax Nat ::= plus(Nat, Nat) [klabel(plus), function]
syntax Int ::= plus(Int, Int) [klabel(plus), function]
```
we could have
```
syntax {S} Join{S, Nat} ::= plus(Meet{S, Int}, Meet{S, Int}) [function]
```
If `S` is instantiated as `Nat`, you recover `syntax Nat ::= plus(Nat, Nat)`. If `S` is instantiated as `Int`, you recover `syntax Int ::= plus(Int, Int)`.

This generalizes in the obvious way. Let `S` be a fresh type variable, and we produce the type of the no-longer-overloaded symbol as follows:
- An argument or return sort which is constant between overloads keep its sort
- An argument sort which differs between overloads is replaced with sort `Meet{S, G}`, where `G` is the greatest sort for the argument among all overloads.
- A return sort which differs between overloads is replaced with sort `Join{S, L}` where `L` is the least sort for the argument among all overloads.

Are there motivating examples for overloading constructors, or would this be sufficient?

**Comment by Baltoli** [comment]
Do we have an integration test for this? Bug report submitted for Jost's example above - use as a frontend test.

**Comment by Baltoli** [comment]
@gtrepta Take a look at the semantics (EVM, WASM, C) to see how onerous it would be to rewrite these rules.

**Comment by Baltoli** [comment]
Via @dwightguth on [Slack](https://runtimeverification.slack.com/archives/C7E701MFG/p1707415053793809), it is important for us to support overloading as it's a useful feature for designing expressive grammars in _expression_ languages.[^1] As a very minimal motivating example, something like the following pair of productions falls out of the C semantics, where `LVal < Exp`.
```k
syntax Exp ::= Exp "." Id
syntax LVal ::= LVal "." Id
```

Pithily, what we're making use of here is the following property:
> overloading is a way to make a constructor have a more specific sort for certain more specific operands

For the constructor `_._`, we want it to have sort `LVal` if its left-hand operand is itself an `LVal`. If we couldn't do this, we'd have to write duplicated rules, or define a predicate function over terms of sort `Exp` that categorises them as `LVal` or not. Supporting this distinction can be done much more efficiently via overloading than it can with a predicate implementation. More formally, what we're supporting here is _subsort overloading_[^2][^3], where the sorts of overloaded symbols belong to the same SCC in the subsort relation (rather than being disconnected).

Part of the confusion here is that the syntax in K for defining and working with overloads is confusing.[^4] We should rationalise the frontend UX for this as follows:
* Permit the `symbol` attribute to take an argument; this argument fully specifies the name of the symbol when generating KORE from a K definition. This behaviour should match what happens using the old `klabel(_)`, `symbol` dance we use currently.
  * Logic for generating klabels internally will need to duplicate work to check for arity-1 or arity-0 forms of `symbol`.
* Add a new `overload(_)` attribute that specifies when a production is an overload of another.
  * The logic for computing the overload poset will temporarily need to account for this syntax as well as the old syntax.
  * We can _validate_ against the list of properties above to check that user-declared overloads are valid (i.e. they have the same shape, a valid subsort relationship, ...), rather than just silently dropping things that have the same klabel but aren't valid overloads.
* Deprecate the old `klabel(_)` attribute.
  * Usual process for doing so; audit existing semantics for usages and update; warnings become errors etc.
  * When we do this, we should also deprecate the zero-arity form of `symbol`.

[^1]: Compared to, for instance, opcode languages. This is why we don't see so many usages of the feature in EVM or WASM, but several in the C semantics. Should we end up designing another similar semantics in the future, it's likely we'd want to use overloading.
[^2]: The [Maude documentation](https://maude.lcc.uma.es/maude-manual/maude-manualch3.html#x15-310003.6) has an example in a context that's somewhat similar to K; discussion of _ad-hoc_ overloading is not relevant.
[^3]: This [paper](https://homepage.divms.uiowa.edu/~fleck/181content/osa1.pdf) includes a fuller motivation.
[^4]: For historical reasons related to backwards compatibility with the OCaml and Java backends. These backends were directly order-sorted, whereas KORE-based modern backends for K all use a many-sorted representation that doesn't deal with subsorting. We compile overloads such to emulate the semantics of the order-sorted environment via injections in the many-sorted environment. See @jberthold's [issue](https://github.com/runtimeverification/haskell-backend/issues/3796) for some nice examples of how we do this compilation.

**Comment by Baltoli** [comment]
To try and answer the questions above: 

> 1. How does overloading work from the user's perspective? Is it a parser feature? Should we document it?

See above for motivation; consider the following example definition:
```k
module TEST
  syntax Unit ::= "(" ")"

  syntax Exp ::= Unit
               | Exp "+" Exp [klabel(_+_)]

  syntax Unit ::= Unit "+" Unit [klabel(_+_)]
endmodule
```

Here, if we don't overload `_+_`, the program `() + ()` does not parse. Because of the overloading, the parser knows how to resolve productions of this form. We should definitely document the feature and how it affects parsing, KORE generation, etc.

> 2. Currently nothing stops the user from accidentally overloading a production (by reusing a `klabel` they are not aware of). Should we add an attribute to enable the user to signal purpose of overloading?

See above.

> 3. The user manual claims that the user "can use the provided `klabel` to refer to that symbol anywhere in the frontend K code". Overloading seems to interfere with this use case. Also, a production that either overloads or is overloaded cannot also have `symbol` (since uniqueness there is enforced). So effectively, `symbol` also means "cannot overload". Should we introduce a dedicated attribute for overloading, and enforce uniqueness of `klabel` as well?

See above.

> 4. In condition (4) of overloading, shouldn't the relation be the other way?

I don't think so; per Dwight's summary of the feature we want to constrain the sort of a constructor to be more specific when its arguments are also more specific.

> 5. Why is attaching the `anywhere` attribute to overloading productions necessary? It seems to be used by the Haskell backend: https://github.com/runtimeverification/k/issues/3946#issuecomment-1930372019.

No idea here; the [PR](https://github.com/runtimeverification/k/pull/216) that does this is very old and I don't understand the Haskell code well enough to explain what it's doing with the attribute.

**Comment by Baltoli** [comment]
Places in the compiler that on a first look, seem to be dealing with resolving overloads in some way:
* Disambiguation chooses the minimal valid parse when choosing between overloads https://github.com/runtimeverification/k/blob/a23c349c30c6718a1c6387b4264a15be09f2b09a/kernel/src/main/java/org/kframework/parser/inner/disambiguation/RemoveOverloads.java#L14

**Comment by Baltoli** [comment]
I think we have covered the overloading feature sufficiently over the last few weeks, so I'm going to close this.
