### ISSUE TITLE
Revisit hook namespaces

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3976]
Related: https://github.com/runtimeverification/pyk/pull/861#discussion_r1482997049

Currently `ModuleToKORE` filters out instances of the `hook` attribute that refer to namespaces that are neither built-in, nor explicitly passed to `kompile --hook-namespaces`. (Also, the `ARRAY` namespace is special cased.)

https://github.com/runtimeverification/k/blob/1e4aa2be6b49ca766e01d78eae0e418a749bb12b/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L946

What's the rationale for explicitly having to state the namespaces that apply? Would it make sense to emit a warning if a `hook` is dropped?

**Comment by Baltoli** [comment]
Weak steelman for the namespacing thing is that maybe you want to be able to select an implementation? Compatibility if a backend doesn't implement hooks??

**Comment by gtrepta** [comment]
This restriction was added in #460 . Digging through the K channel on our slack I found [this conversation](https://runtimeverification.slack.com/archives/C7E701MFG/p1557349615201900). In summary, it looks like specifying hook namespaces on the command line was meant to allow for custom, closed source implementations of hooks that rv-match used, while in the open source c-semantics they would default to a K implementation. This was originally an option in the OCaml backend, but as the llvm-backend began to replace it, it was moved to the frontend.

I'm not totally familiar with how the llvm-backend handles hooked function symbols, but I'm presuming that it uses the `hooked-symbol` attribute to codegen a call to the hook at runtime instead of use rewrite rules.

**Comment by gtrepta** [comment]
The `ARRAY` hooks seem to be special cased because of some friction related to introducing new backends. in the llvm backend at least, they aren't implemented, so the `ARRAY-IN-K` module is used, and the `hook(ARRAY.*)` attributes in `ARRAY-SYNTAX` [are deleted](https://github.com/runtimeverification/k/blob/d29a8d108fd31b20f2ea6ebd4c40d01a5e8bd72c/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L1692-L1694). Relevant PR: #187

**Comment by tothtamas28** [comment]
What are the syntactic restrictions on the `hook` attribute?
* Is it allowed to have `hook` on a production and have rewrite rules for the same production at the same time?
* What happens during kompilation if a symbol is hooked to an external function that's not present?

**Comment by gtrepta** [comment]
The only restriction seems to be that `hook` can only be put on productions and sort declarations. It would probably make sense to have `hook` on productions require the `function` attribute, at least.

> Is it allowed to have hook on a production and have rewrite rules for the same production at the same time?

Yes, it's allowed. The rewrite rules will be used if the hook namespace isn't declared in `--hook-namespaces`.

> What happens during kompilation if a symbol is hooked to an external function that's not present?

Assuming you included the hooks namespace in `--hook-namespaces`, you'll get an error at link time. This is probably the earliest place we can throw an error, as that's the first place all of the binaries come together.

**Comment by Baltoli** [comment]
We can probably remove the array hooks entirely and just make them use the K implementation unconditionally.

**Comment by Baltoli** [comment]
The reason we want to keep the option rather than using the module system is that we would end up with two modules implementing very similar code:
```k
module HOOKS [symbolic]
  syntax K ::= someHook()
  rule someHook() => .K
endmodule

module HOOKS [concrete]
  syntax K ::= someHook() [hook]
endmodule
```

**Comment by Baltoli** [comment]
I think now that the array change has been merged, and we've identified that this is a desirable feature to keep, that we can close this issue and revisit it when we come to do a documentation pass on the feature.
