### ISSUE TITLE
[K-Bug] Cell initialisation not working in a cell collections

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/k#4073]
### What component is the issue in?

llvm-backend

### Which command

- [ ] kompile
- [ ] kast
- [X] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

v6.3.24

### Operating System

MacOS (Intel)

### K Definitions (If Possible)

```k
module SUM-SYNTAX
  imports INT-SYNTAX

  syntax Ints ::= List{Int,","}
endmodule

module SUM
  imports SUM-SYNTAX
  imports INT

  configuration <k> $PGM:Ints </k>
                <ctxes>
                    <ctx multiplicity="*" type="Map">
                        <id> 0 </id>
                        <sum> 0 </sum>
                    </ctx>
                </ctxes>

  rule  <k> I:Int, Is:Ints => Is ...</k>
        <ctx>
            <id> 0 </id>
            <sum> SUM :Int => SUM +Int I</sum>
        </ctx>

endmodule
```

### Steps to Reproduce

```
kompile sum.k
krun -cPGM="1,2,3"
```

### Expected Results

<generatedTop>
  <k>
    .Ints ~> .
  </k>
  <ctxes>
    <ctx>
        <id>0</id>
        <sum> 6 </sum>
    </ctx>
  </ctxes>
</generatedTop>

**Comment by ehildenb** [comment]
I don't think this is a bug, because cell maps initialize as empty. So the initial configuration you'll get is `<k> 1,2,3,.Ints </k> <ctxes> .Bag </ctxes>`

If you add your own initializer, like this:

```

  configuration <k> init 0 ; $PGM:Ints </k>
                <ctxes>
                    <ctx multiplicity="*" type="Map">
                        <id> 0 </id>
                        <sum> 0 </sum>
                    </ctx>
                </ctxes>

syntax KItem ::= "init" Int ";" $PGM:Ints

rule <k> init N ; PGM => PGM </k>
      <ctexs> .Bag => <ctx> <id> N </id> ... </ctx> </ctexs>
```

It may do something more like what you're looking for, using the default value  from your `configuration` declaration to fill in the cell contents for `<sum>`.

**Comment by yanliu18** [comment]
@ehildenb yep, we've had a discussion yesterday, please follow this [thread](https://runtimeverification.slack.com/archives/C7E701MFG/p1709551186778519).

In the manual, it did say `If there are configuration variables present in the cell collection, the initial configuration will start with exactly 1 instance of the cell collection.`.

Though if it is not the case, maybe the manual need to be updated. 

But, feel free to change to other appropriate issue type.

**Comment by Baltoli** [comment]
Unless it's been removed, the `initial` attribute should initialize with one cell instead of zero. We should check this out and update documentation as appropriate.

**Comment by Scott-Guest** [comment]
I've only skimmed the relevant code, but it appears that `initial` is implemented, and I confirmed it works with the above example. I'll update the documentation.

I also noticed a comment and some associated logic:

>    @param hasConfigurationOrRegularVariable true if the initializer for the cell requires a
   configuration variable or a regular variable (when refering directly to configuration
   initializers). This causes cells of multiplicity * or ? to be initialized to a non-empty
   bag, and the initializer to take a Map argument containing the values of the configuration
   variables.

The part about "regular variables" isn't mentioned in the documentation, and I don't fully grasp the implication.

In general, I'm not a big fan of the initialization depending on the presence of config variables - it's surprising that abstracting something out into a compile-time variable subtly changes the semantics. 

A few alternatives to think about
- Only initialize with one cell if `initial` is used, otherwise initialize as empty. Emit an error if a config variable is present without `initial`.
- Always initialize as empty, and just require the user to write their own initializers as @ehildenb described above.
- Provide some alternative syntax to separately specify the sorts of a cell collection and its actual initial values. Maybe something like
```
  configuration <k> $PGM:Ints </k>
                <ctxes>
                    <ctx multiplicity="*" type="Map">
                        <id>Int</id>
                        <sum>Int</sum>
                    </ctx>
                    <ctx>
                         <id> 0 </id>
                         <sum> 0 </sum>
                    </ctx>
                </ctxes>
```
where the first `<ctx>` just specifies the sorts while the following `<ctx>`s are actually inserted into the initial configuration?

**Comment by yanliu18** [comment]
@Scott-Guest that's great. Would you advise how to use this feature? Maybe post your modified example? Thank you.

**Comment by Scott-Guest** [comment]
@yanliu18 Just add the `initial` cell property to your cell collection like so
<pre>
configuration &ltk&gt $PGM:Ints &lt/k&gt
              &ltctxes&gt
                &ltctx multiplicity="*" type="Map" <b>initial=""</b>&gt
                  &ltid&gt 0 &lt/id&gt
                  &ltsum&gt 0 &lt/sum&gt
                &lt/ctx&gt
              &lt/ctxes&gt
</pre>
and now the initial configuration will include one `<ctx>` cell as you originally expected:
```
<k> whatever value the user provides for PGM </k>
<ctxes>
  <ctx>
    <id> 0 </id>
    <sum> 0 </sum>
  </ctx>
</ctxes>
``` 
Let me know if anything is unclear!

**Comment by Baltoli** [comment]
We need the values in the initial configuration in cases where we do configuration completion (see Everett's example above), which would prevent the <cell> Sort </cell> approach from working sensibly.

We should:
* Emit an error when there is a config variable but no `initial` - needs pre-fixing in user semantics as we've been doing for other such cases.
* _Improve the documentation around this behaviour_; we should clarify the various behaviours here in the tutorial and user manual.

Doesn't make sense to insert a value by default.
