### ISSUE TITLE
LLVM backend / scala update breaks terminal ordering

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#4255]
After https://github.com/runtimeverification/k/pull/4171, the ordering of tokens induced by this code in the frontend has changed: https://github.com/runtimeverification/k/blob/99ff4716c1071a4532ae038e6450275b84f6836d/kernel/src/main/java/org/kframework/parser/inner/kernel/Scanner.java#L153-L156

This has a particular effect on regex terminals, where the ordering induced here informs how code is tokenized by the inner parser: if two regex terminals overlap for a particular string, then the one that appears first in the list will be used to tokenize that string.

I noticed this first because it's breaking the MIR semantics update job: https://github.com/runtimeverification/mir-semantics/actions/runs/8704701362/job/23873538708

Here, you can observe the ordering of regex terminals changing after #4171 is applied. Before:
```
r"[a-z][a-zA-Z0-9]*"
r"[0-9]+"
r"[\\+-]?[0-9]+"
...
```
after:
```
r"[0-9]+"
r"[A-Z][a-zA-Z0-9]*"
r"[a-z][a-zA-Z0-9]*"
...
```

This ends up causing a problem when tokenizing cell attributes in XML syntax for the MIR semantics; the reordering causes the attribute strings to be lexed as _MIR_ strings rather than _K_ strings, producing difficult-to-follow parse errors like:
```
Error: Error] Inner Parser: Parse error: unexpected token '""' following token '='.
kmir>   Source(/build/kbuild-mir-semantics-wk7pw2_3/mir-semantics/include/mir-semantics/mir-configuration.md)
kmir>   Location(22,22,22,24)
kmir>   22 |        <returncode exit=""> 4 </returncode>     // the simulator exit code
kmir>      .                         ^~
```

Reproduction steps:
```console
$ git clone git@github.com:runtimeverification/mir-semantics.git --branch _update-deps/runtimeverification/k
$ cd mir-semantics
$ kup install k --version v7.0.3
$ kompile kmir/k-src/mir-configuration.md
[Warning] Compiler: Could not find main syntax module with name
MIR-CONFIGURATION-SYNTAX in definition.  Use --syntax-module to specify one.
Using MIR-CONFIGURATION as default.
$ kup install k --version v7.0.4
$ kompile kmir/k-src/mir-configuration.md
[Error] Inner Parser: Parse error: unexpected token '""' following token '='.
	Source(/Users/brucecollie/code/mir-semantics/kmir/k-src/mir-configuration.md)
	Location(22,22,22,24)
	22 |	    <returncode exit=""> 4 </returncode>     // the simulator exit code
	   .	                     ^~
[Error] Inner Parser: Parse error: unexpected token '"*"' following token '='.
	Source(/Users/brucecollie/code/mir-semantics/kmir/k-src/mir-configuration.md)
	Location(63,30,63,33)
	63 |	      <function multiplicity="*" type="Map">
	   .	                             ^~~
[Error] Inner Parser: Parse error: unexpected token '"*"' following token '='.
	Source(/Users/brucecollie/code/mir-semantics/kmir/k-src/mir-configuration.md)
	Location(93,33,93,36)
	93 |	        <localDecl multiplicity="*" type="Map">
	   .	                                ^~~
[Error] Inner Parser: Parse error: unexpected token '"*"' following token '='.
	Source(/Users/brucecollie/code/mir-semantics/kmir/k-src/mir-configuration.md)
	Location(153,32,153,35)
	153 |	      <basicBlock multiplicity="*" type="Map">
	    .	                               ^~~
[Error] Compiler: Had 4 parsing errors.
[Warning] Compiler: Could not find main syntax module with name
MIR-CONFIGURATION-SYNTAX in definition.  Use --syntax-module to specify one.
Using MIR-CONFIGURATION as default.
```

**Comment by Baltoli** [comment]
This should be turned into a regression test once the root cause is identified.

**Comment by Scott-Guest** [comment]
For the `MIR-CONFIGURATION-CONFIG-CELLS` parsing module, I confirmed that the value of `tokens` in
https://github.com/runtimeverification/k/blob/99ff4716c1071a4532ae038e6450275b84f6836d/kernel/src/main/java/org/kframework/parser/inner/kernel/Scanner.java#L153-L156
is exactly the same before and after #4171. Thus, any change in `ordered` is simply due to flakiness in the set iteration order.

In particular, both [`String` in `domains.md`](
https://github.com/runtimeverification/k/blob/afa82dcd698ed78a985a41c3379e32a4f9fc69b8/k-distribution/include/kframework/builtin/domains.md?plain=1#L1693) and [`StringLiteral` in `mir-lexer-syntax.md`](https://github.com/runtimeverification/mir-semantics/blob/db4b053243040a5a0d11c92074095ccf1bb5764c/kmir/k-src/mir-lexer-syntax.md?plain=1#L40) have the default precedence of `0`, so their relative order is not specified.

AFAIK this is the expected behavior of the lexer, and there is no actual bug here. The behavior before was correct only by chance, and the proper solution is to explicitly mark `StringLiteral` as a lower precedence, e.g., `prec(-1)`. I've confirmed this fixes the error.

**Comment by Baltoli** [comment]
> Thus, any change in ordered is simply due to flakiness in the set iteration order.

Makes sense to me; even small changes to the code in my reproduction of the issue would stop it happening.
