### ISSUE TITLE
Syntax to update a map with other elements of the map itself?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#450]
I'm looking for something like `S[ r |-> S(v)]`. i.e. if `S` maps `v` to `x`, then update `S` to map `r` to `x`. In other words, I'd like a way to call the map with some value within an update rule. Is this possible in K?

**Comment by dwightguth** [comment]
`S [ r <- S[v] ]`

**Comment by LaifsV1** [comment]
Ooh, I didn't try that. Thank you very much! What happens if `S[v]` is empty? 
edit: as in, if `v` hasn't been mapped to anything in `S`.

edit2: testing the syntax, I can't make it compile with expressions involving `S[v]`.
I have rule:
```
  rule <k> X1:KVar + X2:KVar => !X:KVar ... </k>
       <state> Sigma => Sigma[!X <- 1 + 1] </state>
```
which compiles.
But the rule:
```
  rule <k> X1:KVar + X2:KVar => !X:KVar ... </k>
       <state> Sigma => Sigma[!X <- Sigma[X1] + Sigma[X2]] </state>
```
does not compile. Am I using the square brackets wrong?

**Comment by dwightguth** [comment]
you should not use the syntax `S[v]` in a context where you don't know whether v is in the domain of S. The meaning of such an expression in the theory of K is bottom, ie, no such term exists, and in theory it would make the entire configuration nonsatisfiable and thus removed from the list of results. But in practice this is likely to be buggy. You are better off writing rules that either explicitly match on v as a key, or else writing a side condition that says `v in_keys(S)`.

The reason your rule does not parse is that K does not support polymorphic sorts yet. Thus, the sort of `Sigma` is `Map` and not `Map{KVar, Int}`, which means the sort of `Sigma[X1]` is `KItem`, not `Int`. You have two choices: you can explicitly cast the map lookup to an int like so (the configuration will get stuck if an int does not in fact exist there): `{Sigma[X1]}:>Int`.

A more idiomatic solution would be to rewrite the rule to explicitly match on the keys of Sigma, like so:
```
rule <k> X1:KVar + X2:KVar => !X:KVar ... </k>
     <state>... X1 |-> I1 X2 |-> I2 (.Map => !X |-> X1 +Int X2) ...</state>
```

Note my use of +Int instead of +. +Int is the addition over the theory of integers. + is most likely an expression you defined in the grammar of your language, which I suspect is not what you intended.

**Comment by LaifsV1** [comment]
Ah, I see. Thanks for the reply!
My actual intention was for `Sigma` to be a map from variables to symbolic expressions. I currently am using it as a symbolic environment. So I my intention was actually to have the symbolic term `X1 + X2` if `X1` and `X2` are variables. But I think I understand now why the rule does not parse. Thanks!
