### ISSUE TITLE
What does #False executing krun mean?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#454]
When executing `krun` on a sample program for a lambda calculus, I get `#False` as an output. What does this mean?

**Comment by dwightguth** [comment]
It's a little hard to answer this question without the context of the exact command you ran, but I can take a guess, and if I'm wrong, just let me know what the exact command was and I should hopefully be able to give you a better idea.

When you pass the `--pattern` command to krun, it is telling krun to filter its normal set of output states by whether or not they match some pattern. For example, I could say something like `krun foo.lambda --pattern "<k> I:Int </k>"` and it would return only the output states in which the K cell contained nothing but an integer. If no such output states exist, it would return `#False`, indicating that the mathematical meaning of your query is bottom, ie, the empty set of terms.

**Comment by LaifsV1** [comment]
Ah. That is very useful. The pattern option is exactly what I need. I actually ran `krun --search foo.lambda`, and it returned False. By default, what pattern does search use? I thought it lists all terminal configurations. Why would it return false?

**Comment by dwightguth** [comment]
That is definitely odd. The default search pattern it uses is simply to return the entire configuration no matter what. I would not expect to see `#False` returned by a search unless you specified a search pattern. Can you provide me with a self contained example that reproduces the behavior so I can take a look?

**Comment by LaifsV1** [comment]
Thanks! I will provide an example as soon as I can!

**Comment by LaifsV1** [comment]
Here's a small example.
The K file `test.k`:
```
module TEST-SYNTAX
  imports DOMAINS-SYNTAX

  syntax Term  ::= "assert" Term                         [strict(1)]
                 | "fail"
                 | Val
		 > Term ";" Term                         [strict(1), right]
                 | "(" Term ")"                          [bracket]

  syntax Val    ::= Int | "()"
endmodule

module TEST
  imports TEST-SYNTAX
  syntax KResult ::= Val

  configuration <T>
                  <k> $PGM:Term </k>
	        </T>
		
  rule fail ~> _ => fail
  rule assert I:Int => () requires I =/=Int 0
  rule assert 0 => fail
  rule V:Val ; T2:Term => T2
endmodule
```
which I ran on program `test.test`:
```
assert( 0 );assert( 1 )
```
The output is `#False`.

Edit: the context for this example is that I was trying to write a naive form of halting execution when an error is encountered. In this case, when an assertion fails, and the term `fail` appears on the evaluation context, it should halt execution and return `fail`.

**Comment by dwightguth** [comment]
I figured out why you're seeing this behavior. This is actually the correct behavior of krun for this scenario, although in this case it is occurring due to what I believe to be a bug in your semantics, which you should now be able to fix.

The problem here is the rule `rule fail ~> _ => fail`. This rule desugars into the following:
```
rule <T> <k> fail ~> Var1 ~> Var2 </k> </T> => <T> <k> fail ~> Var2 </k> </T>
```

In this case, if Var1 and Var2 are both .K, then this is equivalent to the following rule:
```
rule <T> <k> fail </k> </T> => <T> <k> fail </k> </T>
```

As you can see, this is rewriting the current term to itself. In this case, because the configuration is not changing at all, krun was able to detect that rewriting didn't terminate, and so it returned `#False`, indicating that there exist no output states for this input configuration. Perhaps there should be a nicer message here, but krun is technically behaving soundly.

I believe what you meant to write was the following:

``` rule <k> fail ~> K:K => fail </k> requires K =/=K .K```

**Comment by LaifsV1** [comment]
Ah. I see. I was suspecting this, but wasn't sure if the output of krun was correct behaviour. I had originally fixed this bug with the rule `fail ~> K:KItem => fail`. What does `.K` mean in `K =/=K .K`? 

Edit: I think I understand. It's nothing of type K, right? So fail can't be followed by nothing.

**Comment by LaifsV1** [comment]
On the topic of `--search` and `--pattern`:

1. when running `--search`, some results are of the form: `isKResult ( V0 ) ==K true`. What does this mean?
2. when running `--search` and `--pattern "<k> X:KVar </k>"`, it doesn't output the whole configuration, but outputs something of the form `X ==K _3 #Or  X ==K _6`. Is there a way to output the whole configuration?
3. sometimes `krun` outputs `#And` instead of `#Or`. My understanding is that `#Or` means the configurations are separate paths. But how can different configurations occur with `#And`?
4. what does `#True` mean when running `krun` with the `pattern` option?

**Comment by dwightguth** [comment]
.K is the unit of the list type that the `K` sort represents whose `cons` operator is `~>`. We allow users to write terms of sort K as if they were an associative list, but it's actually implemented as a cons list under the hood and matching elements off the tail is not supported (for that, you need the List sort).

I don't believe we have a way to output the entire configuration instead of a substitution, but if you write a pattern that completes to the top cell with no anonymous variables, you can of course infer the entire configuration from the substitution.

`#And` means that there are multiple variables in the substitution and the conjunction of all of them is a single search result. `#True` means that the pattern matched but generated the empty substitution. A term like `isKResult(V0) ==K true` in the substitution means that you have some symbolic term that ended up in the output substitution but was unable to be fully resolved.

**Comment by LaifsV1** [comment]
Thanks for the reply! I'm closing this as it has been answered.
