### ISSUE TITLE
Set non-membership and rules excluding certain sorts?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#463]
Is there a way to pattern match on whether an element `E` is definitely not in some set `S`? Additionally, if I have a rule: `rule V:Val => OP`, is there a way to apply this rule only if `Val` is not an instance of, say, `KVar`?

**Comment by dwightguth** [comment]
`requires notBool (E in S)` is the only way currently. You cannot do this via direct pattern matching because K does not support negation patterns in rule left-hand-sides.

**Comment by dwightguth** [comment]
in terms of the second one, you can say `requires notBool isKVar(V)`

**Comment by LaifsV1** [comment]
Thanks for the reply! What about finding out whether something is in the domain of a map?
e.g. `E in dom(S)`?

**Comment by dwightguth** [comment]
You can get the domain of a map by saying `keys(M)` which means technically you can check whether something is in the domain of a map by saying `E in keys(M)`, but this is rather inefficient because it has to construct an entirely new collection. For a simple membership check, we have an explicit function for this: `E in_keys(M)` (note the underscore instead of a space)

**Comment by LaifsV1** [comment]
Ah. That's very helpful. Thanks!
