### ISSUE TITLE
kprove with llvm backend

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#493]
essentially we want to extend the llvm backend to provide support for kprove. what this would do is use the haskell backend to concretize the lhs of each claim into a set of N concrete terms that satisfies the requires clause of the claim. then we apply the newly created substitution to the lhs of the original rule, execute the new rules under a semantics that rewrites the unsubstituted rhs to #True (with a side condition that the bound variables on the rhs are equal to the original substitution, and at a higher matching priority than any axiom), and print the output. we would need to warn the user somehow that this #True is not a guarantee but simply a best guess about whether the claim holds.

Everett suggested we keep this code proprietary. maybe we need a special "fuzzing" backend?

**Comment by nishantjr** [comment]
Would it be reasonable to have the case where the LHS is already concrete, open-source? This would be extremely useful for unit-testing internal infrastructure used as part of the language implementation, but not exposed by the language directly. I have been using this with varying levels of success on the java backend, but failures can be hard to understand because of Java-backend weirdness.

**Comment by radumereuta** [comment]
We will implement these functionality through k-repl.
