### ISSUE TITLE
specs with large nested expressions fail to parse

### ISSUE THREAD

**Issue by mhhf** [runtimeverification/k#496]
Specs like [this](https://dapp.ci/k-dss/bf8e45e06db4d94ff89b/7025479a400a431514b92fba42fe31c46629c6d084560c7dbbc5cb73c5535b16.k) which contain a large arithmetic expression fail to parse - kprove runs on all cores on 100% cpu forever and max-out the RAM.
Shorter gas expressions work fine, but as soon as they get over a certain threshold k fails to parse them.
I tried to rewrite them as kast prefix expressions, but this fails due to ambiguities: https://github.com/kframework/evm-semantics/issues/286
Is there anything i can do to make it work?

**Comment by ehildenb** [comment]
@denis I see a lot of `#if_#then_#else_#fi` in the expression, which maybe are coming from rules like:

```
    rule Cgascap(SCHED, GCAP, GAVAIL, GEXTRA) 
      => #if GAVAIL <Int GEXTRA orBool Gstaticcalldepth << SCHED >> #then GCAP #else minInt(#allBut64th(GAVAIL -Int GEXTRA), GCAP) #fi  [concrete] 
 
    rule Csstore(SCHED, NEW, CURR, ORIG) 
      => #if CURR ==Int NEW orBool ORIG =/=Int CURR #then Gsload < SCHED > #else #if ORIG ==Int 0 #then Gsstoreset < SCHED > #else Gsstorereset < SCHED > #fi #fi 
      requires Ghasdirtysstore << SCHED >>  [concrete] 
    rule Csstore(SCHED, NEW, CURR, ORIG) 
      => #if CURR ==Int 0 andBool NEW =/=Int 0 #then Gsstoreset < SCHED > #else Gsstorereset < SCHED > #fi 
      requires notBool Ghasdirtysstore << SCHED >>  [concrete] 


```

Instead of using the RHS of the above rules, can you use the LHS instead??
It should make for shorter expressions I guess.
So then your formula for gas would contain things like `Cgascap` and `Csstore` instead of the expanded `#ite` expressions.
I guess specifying the `CURR` and `ORIG` storage may be tricky.

**Comment by dwightguth** [comment]
I suspect this is because of the very long sequence of andBool in the side condition of one of your rules. Long sequences of associative infix binary operators are badly handled by the k parser currently. It is a known issue but unfortunately I do not have the technical expertise to fix it at this time. I would suggest you deliberately insert left or right associativity with nested parentheses.

**Comment by mhhf** [comment]
@dwightguth 
> I would suggest you deliberately insert left or right associativity with nested parentheses.

The only place I see it in the above spec are the couple of lines after the require statements that are not wrapped in parentheses. Doing so didn't helped with getting it parsed, so i don't think its the andBools that causing trouble but rather the nested if_then_else

**Comment by MrChico** [comment]
Another, possibly related problem is that when interrupting the parsing of these expressions, (like with `C^c`) it doesn't properly kill the java process.

**Comment by ehildenb** [comment]
The frontend has changed pretty dramatically since this issue, as well as domains.md and kast.md. If this is still an issue, please re-open.
