### ISSUE TITLE
Weird behaviour using a variable named `size` in the java backend

### ISSUE THREAD

**Issue by MrChico** [runtimeverification/k#708]
I ran into some weird behaviour when using a variable named `size` in a custom defined semantics. Renaming the variable to anything else resolves the issue. It seems like the identifier `size` has some special status in the java backend.

Is there a way to override this weird behavior?

**Comment by dwightguth** [comment]
uh, variables can't start with a lowercase letter. Does `Size` work?

**Comment by ehildenb** [comment]
https://github.com/kframework/k/pull/709/files

Looks like you mean `Id` `size`, _not_ K variable `size`.

**Comment by MrChico** [comment]
> https://github.com/kframework/k/pull/709/files
> 
> Looks like you mean `Id` `size`, _not_ K variable `size`.

Yes. An object language variable. Not K variable.

**Comment by ehildenb** [comment]
Well my guess is that it's conflicting with the `size` token defined in several places in `domains.k`. You probably would have the same issue with a variable called `values` or `keys`.

I'm not sure what the correct way to fix this is, because I'm not sure if the lexer is deciding that `size` is from the production from `SET` or `MAP`, or if the parser is making that decision. If it's the parser, then you can try the `prefer` attribute here `syntax Int ::= "function" Id`.

**Comment by dwightguth** [comment]
You have run into a known limitation of the K parser. the main module of any K definition automatically imports the MAP module in order to construct the initial configuration, and the MAP module defines the size() function. This introduces a lexical ambiguity between the size token which is part of the size(Map) function, and the size token of sort Id. Unfortunately K cannot currently disambiguate ambiguous tokenizations.

This is not something we currently have the bandwidth to fix, but you can work around it quite easily. The following definition does not import the Map module from the syntax module of the definition and thus is able to parse `size` as an Id:

```
module TEST-SYNTAX
imports ID
syntax Int ::= "function" Id
endmodule

module TEST
imports TEST-SYNTAX
endmodule
```

**Comment by ehildenb** [comment]
@MrChico if this works, please close this issue and associated PR.

**Comment by MrChico** [comment]
Yup. This workaround works. Thanks
