### ISSUE TITLE
No support for exponentials in rule requirements

### ISSUE THREAD

**Issue by mhhf** [runtimeverification/k#84]
I've problems with `^Int` expressions in an evm-semantics proof. They can't be translated into z3 and therefore the `impliesSMT` function crashes: this blocks from having expressions with `^Int` in require statements of lemmas:
e.g. I've a precondition a the circularity rule looking like this:
```...
X ^Int (2 +Int N) <Int pow256
1 <=Int X
X <Int pow256
...
```

at one point in the proof I multiply X*X which leaves `chop(X *Int X)` on the stack
in order to reason about it i have the following lemma:
```
rule chop(X *Int X) => X *Int X
  requires X ^Int (2 +Int N) <Int pow256
```
Since the actual proof is for an implementation of fixed-point exponentiation by squaring I don't see how omitting `^Int` expressions in requirements is possible.

**Comment by ehildenb** [comment]
Where is `N` coming from in the requires clause of the lemma?

**Comment by mhhf** [comment]
Hmm, I thought it would be bound by the term/constraint context it is applied to:
at the time of this rule application it is constraint by:
```
0 <=Int N ==K true
N <Int pow256 ==K true
N ==K 0 ==K false
```
and appears in the term stack.

A rule like [1] does the trick: but removes the lhs from the constrains, but its needed in other parts as well.
```
rule X ^Int (2 +Int N) <Int pow256 => X *Int X <Int pow256        // [1]
    requires 0 <=Int N
```
Also binding it in the requirements won't solve the trick:
```
rule chop(X *Int X) => X *Int X
  requires X ^Int (2 +Int N) <Int pow256
  andBool 0 <=Int N
```

**Comment by MrChico** [comment]
@ehildenb , this is in the context of a proof of `X ^ N`. So `N` comes from a value on the stack, the exponent.

**Comment by ehildenb** [comment]
Hmmm, is the error you're seeing "missing SMTLIB translation" or a Z3 crash because it cannot translate `_^Int_`?

You could try adding the attribute `smtlib(expFunc)` or the like to the line declaring `_^Int_` in `k-distribution/include/builtin/domains.k`. If you're using the submodule version of K for KEVM, then you'll want to:

1.  Change into the submodule directory, edit the file.
2.  `git add k-distribution/include/builtin/domains.k ; git commit -m 'test commit'`
3.  Change back to KEVM directory.
4.  `git add .build/k ; git commit -m 'test commit'`

Then `make deps`, and `make build`.

This will give uninterpreted function semantics to `_^Int_`. If you've already tried this, let me know.

By the way, if you have two rules/claims with the same variable `N` in each of them, there should be no relation between the two `N`, as they are *bound* occurrences (each rule implicitly has a "forall" quantifier around it). I'm not sure if this is what you're meaning when you say that you have an `N` show up in the proof context because of another claim, and you're trying to use this lemma to reason about it directly. The reason the lemma would be applying is because it matches directly (ie. the `N` in the lemma would be bound to the `N` in the proof context). So in the initial version of the lemma you gave (not [1]), the `N` is coming from nowhere (fresh unconstrained integer).

Of course, requiring `X ^Int (2 +Int N) <Int pow256` is always satisfiable with choice `N ==Int -2`. But if we aren't even translating `_^Int_` in the query to Z3, then the entire point is moot, because then Z3 won't know that property of `_^Int_` anyway.

Also, looking at `domains.k`, it seems that we do translate other operators directly to operators that Z3 is aware of. It would probably be good to see if Z3 actually has a proper exponentiation and translate directly to that if possible (which would be better than uninterpreted function). May not though.

**Comment by ehildenb** [comment]
Could you provide a link to the entire proof spec you're working with?

**Comment by dwightguth** [comment]
Preliminary research suggests that integer exponentiation in Z3 is done via the `^` operator, but that nonlinear integer arithmetic is undecidable and the solver for nonlinear integer arithmetic is disabled by default as it decreases the effectiveness of solving linear integer arithmetic problems.

I am making a pull request to add the `smtlib(^)` attribute to `^Int` easily enough, but that is unlikely to actually solve your issue. You would also need to try using `check-sat` with the `qfnra-nlsat` solver for it to be very effective.

Therefore, I will also add an option to kprove to set the z3 proof tactic, which will hopefully solve your issue (although it may fall outside of z3's heuristics for nonlinear arithmetic). I would suggest for maximum effectiveness that you update to the latest version of z3 and pass `(and-then qfrna-nlsat default))` as the value of the flag, once the code is ready.
