### ISSUE TITLE
pretty printing error for LLVM debugger

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#958]
Used: k-master, Ubuntu 19.10
```
module TEST
  imports DOMAINS
  syntax Path ::= r"[\\\\./a-zA-Z0-9_-][\\\\./a-zA-Z0-9_-]*" [token]

  configuration
      <k> 0 </k>
      <p> $PATH:Path </p>
    
  rule <k> _:Int => .K </k>
endmodule
```
`kompile test.k -ccopt -g -ccopt -O1` // I still haven't figured out why `-O0` doesn't work on my machine
`krun --output kast -cPATH=.build/kink --debugger`
```
(gdb) break definition.kore:step
Breakpoint 1 at 0x28e2b0
(gdb) run
Breakpoint 1, 0x000000000028e2b0 in step (subject=
    `<generatedTop>{}`(`<k>{}`(`kseq{}`(`inj{Int{}, KItem{}}`(#token("0", "Int")),dotk{}(.KList))),`<generatedCounter>{}`(#token("0", "Int")),`<p>{}`(#token(".build/kink","Id"))))
(gdb) continue
(gdb) q
`<generatedTop>`(`<k>`(.K),`<generatedCounter>`(#token("0","Int")),`<p>`(#token(".build/kink","Path")))
```
The problem is the sort of the token from `<p>` reads `Id`, although I haven't used Id anywhere in this definition. Considering the final output reads fine, I think it's a pretty printing error in LLVM.

**Comment by radumereuta** [comment]
Bug #2:
```
(gdb) break domains.k:889
Breakpoint 1 at 0x293c30: file /home/radu/work/k/k-distribution/target/release/k/include/builtin/domains.k, line 985.
```
I said I want a breakpoint at line 889, why is it saying line 985?

**Comment by dwightguth** [comment]
The first is a known issue associated with pretty printing in gdb and I don't view it as a priority at this time, since it does not interfere with the ability to visualize the term when debugging. The second is happening because line 985 is the first line after line 889 that has debug information associated with it such that a breakpoint could be set. This is the normal behavior of gdb. I will keep the issue open to track the issue associated with pretty printing in gdb, but there are higher priorities on my time at the moment. If you want to look into fixing it yourself, essentially what would be required is to modify the visitChildren function in the llvm backend so that it uses global variables to store the data about the children of sorts by their tag, so that that data can be looked up in gdb. I can give you more information if you're interested in working on it.
