### ISSUE TITLE
:=K, :/=K operators don't work on symbolic terms (kprove)

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#991]
The following PR fails both on Java and Haskell backend: https://github.com/kframework/k/pull/989

The cause is that negative case for `:=K` is encoded as `[owise]` rule, and owise rules are not executed on symbolic terms. At least not for functions in Java Backend. In Java Backend there might be additional issues, so it's better to test on Haskell.

These tests, for concrete execution, pass for Java backend: https://github.com/kframework/k/tree/master/k-distribution/tests/regression-new/equals-pattern

**Comment by dwightguth** [comment]
I'm not entirely sure what you expect someone to do about this. A function like this can't be encoded to have a negative case without the owise attribute or something very much like it (not patterns). If the backend doesn't choose to evaluate the negative case on symbolic terms, that's the backend's choice, but there's nothing the frontend can do at that point to make the term evaluate. As I understand, there are some fairly good reasons why you don't want function evaluation to introduce branching, which is what this would require. So this behavior would seem to be by design. If you want to clarify what exactly you want done, I might be able to address the concern more specifically, though.

**Comment by denis-bogdanas** [comment]
Yes you are probably right. You suggested `:=K` as replacement for `#getKLabelString`. It turned out this operator is not a replacement. Fortunately for now I eliminated the need for `#getKLabelString` through other means but the need might appear in future.
